// Copies the built game (../dist/stick-clash.html) into the app as a TypeScript
// module exporting the HTML string, so it is bundled and works offline.
// Runs on `npm run sync`, and automatically before start/ios/export and after install.
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = fileURLToPath(new URL('../../dist/stick-clash.html', import.meta.url));
const OUT_DIR = fileURLToPath(new URL('../src/generated/', import.meta.url));
const OUT = OUT_DIR + 'gameHtml.ts';

const PLACEHOLDER = `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1">
<body style="background:#10121a;color:#ccd;font:16px -apple-system,sans-serif;display:grid;place-items:center;height:100vh;margin:0;text-align:center">
<p>Game not built yet.<br>Run <code>node build.mjs</code> in the game folder, then <code>npm run sync</code>.</p></body>`;

function write(html, note) {
  const hash = createHash('sha256').update(html).digest('hex').slice(0, 12);
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    OUT,
    `// GENERATED by scripts/sync-game.mjs. Do not edit. ${note}\n` +
      `export const GAME_HTML_HASH = ${JSON.stringify(hash)};\n` +
      `export const GAME_HTML: string = ${JSON.stringify(html)};\n`,
  );
  return hash;
}

if (existsSync(SOURCE)) {
  const html = readFileSync(SOURCE, 'utf8');
  const hash = write(html, 'Source: ../dist/stick-clash.html');
  console.log(`[sync] Bundled game: ${(html.length / 1024).toFixed(0)} KB (sha ${hash}) -> src/generated/gameHtml.ts`);
} else if (existsSync(OUT)) {
  // e.g. on an EAS build server, where only mobile/ is uploaded: keep the last synced copy.
  console.warn('[sync] ../dist/stick-clash.html not found; keeping existing src/generated/gameHtml.ts');
} else {
  write(PLACEHOLDER, 'PLACEHOLDER: game was not built when this ran.');
  console.warn('[sync] ../dist/stick-clash.html not found; wrote a placeholder page. Run `node build.mjs` in the game folder.');
}
