/* ===== S-4 saves: every key through one store. Each write keeps two checked copies (sequence, time, checksum) in browser storage; as the artifact the runtime db keeps the player's private copy and browser storage is its cache; a failed save says so and offers a backup file ===== */
const LOCK_KEY='voxellinks.lock',CAR_KEY='voxellinks.career';
const VS=(()=>{let LS=null;try{LS=localStorage;LS.getItem('voxellinks.probe')}catch(e){LS=null}
  /* each key: the value itself (as every earlier build wrote it) and a backup copy "VS1|seq|time|checksum|value" written after it; a read takes the value unless it is damaged — unreadable and not matching its backup's checksum — and then the backup */
  const M=new Map(),Q=new Map(),FK=new Set(),st={warn:null,info:null,ro:null,roB:false,fails:0,restored:[],remote:'off'},cl=()=>typeof window!=='undefined'&&window.claude&&typeof window.claude.use==='function'?window.claude:null,fnv=s=>{let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  const BAK=k=>k+'.b',isBak=k=>k.startsWith('voxellinks.')&&k.endsWith('.b'),wrap=(q,t,v)=>'VS1|'+q+'|'+t+'|'+fnv(v)+'|'+v,
    unwrap=s=>{if(s==null||!s.startsWith('VS1|'))return null;const p=s.split('|',4);if(p.length<4)return null;const v=s.slice(p.join('|').length+1);return fnv(v)===p[3]?{q:+p[1],t:+p[2],h:p[3],v}:null},
    raw=k=>{try{return LS?LS.getItem(k):null}catch(e){return null}},json=v=>{try{JSON.parse(v);return true}catch(e){return false}};
  function read(k){if(FK.has(k)&&M.has(k))return M.get(k);const v=raw(k),b=unwrap(raw(BAK(k)));if(v!=null&&(!b||b.h===fnv(v)||json(v)))return{v,t:b&&b.h===fnv(v)?b.t:0,q:b?b.q:0};
    if(b){if(!st.restored.includes(k)){st.restored.push(k);st.info='A damaged save was restored from its backup copy ('+st.restored.map(k=>k.replace('voxellinks.','')).join(', ')+').'}return{v:b.v,t:b.t,q:b.q}}
    return M.has(k)?M.get(k):null}
  function keys(){const out=new Set();if(LS)try{for(let i=0;i<LS.length;i++){const k=LS.key(i);if(k!=null&&!isBak(k)&&k!==LOCK_KEY&&k!=='vl.tab')out.add(k)}}catch(e){}for(const k of M.keys())out.add(k);return[...out]}
  function reload(){st.restored=[];st.info=null;for(const k of keys())read(k)}
  function fail(k,e){st.fails++;if(k)FK.add(k);const qf=!!(e&&/quota/i.test(e.name+' '+e.message));st.warn=st.remote==='on'?null:'Your progress could not be saved in this browser'+(qf?' (storage is full)':' (storage is blocked)')+'. Download a backup to keep it.';vsBanner();if(K.up)VL.emit('save:failed',{key:k,quota:qf,warn:st.warn})}
  /* keep: a write that is not the player's (a migration's write-back, a copy, a boot-time default) keeps the old time, so a newer value from the runtime store still wins */
  function setItem(k,v,keep){v=String(v);const o=read(k),q=(o?o.q:0)+1,t=keep?(o?o.t:0):Math.max(Date.now(),(o?o.t:0)+1);M.set(k,{v,t,q});let ok=false;
    if(!LS)fail(k,null);else try{LS.setItem(k,v);ok=true;FK.delete(k);try{LS.setItem(BAK(k),wrap(q,t,v))}catch(e){}if(st.fails&&!FK.size){st.fails=0;st.warn=null;vsBanner()}}catch(e){fail(k,e)}push(k);return ok}
  function removeItem(k){M.delete(k);FK.delete(k);if(LS)try{LS.removeItem(k);LS.removeItem(BAK(k))}catch(e){}push(k)}
  /* the runtime store (as the artifact): one private document per key (bests share one), large values in chunks; one write in flight, the latest value wins */
  let col=null,busy=false;const GRP=k=>/^voxellinks\.(c\d+\.|k\d+\.)*\d+\.\d+$|^voxellinks\.hb\./.test(k)?'voxellinks.bests':k,CH=200000;
  function push(k){if(!col)return;Q.set(GRP(k),1);if(!busy)flush()}
  async function flush(){busy=true;try{while(Q.size&&col){const id=Q.keys().next().value;Q.delete(id);const kv={};for(const k of keys())if(GRP(k)===id){const r=read(k);kv[k]=[r.t,r.v]}
        const s=JSON.stringify(kv),n=Math.max(1,Math.ceil(s.length/CH)),t=Date.now();try{if(s==='{}')await col.doc(id).delete();else for(let i=n-1;i>=0;i--)await col.doc(i?id+'~'+i:id).set(i?{t,s:s.slice(i*CH,(i+1)*CH)}:{t,n,h:fnv(s),s:s.slice(0,CH)})}
        catch(e){const c=e&&e.code;if(c==='unavailable'||c==='resource_exhausted'){Q.set(id,1);await new Promise(r=>setTimeout(r,c==='unavailable'?2000:15000))}else{col=null;st.remote=c==='quota_exceeded'?'full':'readonly';if(st.fails)fail('',null)}}}}finally{busy=false}}
  /* at start, as the artifact: read the player's documents and take whatever is newer on each side */
  async function remote(){const c=cl();if(!c)return;let changed=false;if(st.remote==='off')st.remote='wait';try{const[d,u]=await Promise.all([c.use('db'),c.use('user')]);if(!d||!u)return;const id=await u.id();if(!id)return;
      const C=d.collection('data/users/'+id),snap=await C.get(),docs=new Map(snap.docs.map(x=>[x.id,x.data()]));const seen=new Map();
      for(const[id0,b]of docs){if(id0.includes('~')||!b||!b.n)continue;let s=b.s||'';for(let i=1;i<b.n&&s!=null;i++){const x=docs.get(id0+'~'+i);s=x&&x.t===b.t?s+x.s:null}if(s==null||fnv(s)!==b.h)continue;let kv;try{kv=JSON.parse(s)}catch(e){continue}
        for(const k in kv){const[t,v]=kv[k],o=read(k);seen.set(k,t);if(!o||t>o.t){M.set(k,{v,t,q:(o?o.q:0)+1});if(LS)try{LS.setItem(k,v);LS.setItem(BAK(k),wrap((o?o.q:0)+1,t,v))}catch(e){}changed=true}}}
      col=C;st.remote='on';if(st.warn){st.warn=null;vsBanner()}for(const k of keys()){const r=read(k);if(!seen.has(k)||r.t>seen.get(k))Q.set(GRP(k),1)}if(Q.size)flush()}catch(e){}finally{if(st.remote==='wait')st.remote='off';if(onRemote)onRemote(changed)}}
  /* 'wait' until the first merge is done (whatsNew waits for it); onRemote(changed) runs once it is */
  let onRemote=null;if(cl())st.remote='wait';reload();
  return{getItem:k=>{const r=read(k);return r?r.v:null},setItem,removeItem,key:i=>keys()[i]??null,get length(){return keys().length},reload,remote,fail,note:(t,b)=>{st.ro=t;st.roB=!!b;vsBanner()},status:()=>Object.assign({},st),set onRemote(f){onRemote=f}}})();
const saveStatus=()=>VS.status();
/* the banner: one line at the top when a save failed, with a backup file of everything the game keeps */
function vsBanner(){if(typeof document==='undefined'||!document.body)return;let el=document.getElementById('saveWarn');const s=VS.status(),w=s.warn||s.ro||s.info;
  if(!el){if(!w)return;el=document.createElement('div');el.id='saveWarn';el.style.cssText='position:fixed;top:8px;left:50%;transform:translateX(-50%);z-index:60;max-width:min(92vw,640px);padding:8px 12px;border-radius:10px;background:color-mix(in srgb,var(--red600) 92%,transparent);color:var(--white);font:13px/1.35 system-ui,sans-serif;display:flex;gap:10px;align-items:center';
    el.innerHTML='<span id="saveWarnT"></span><button class="sec" id="saveWarnB">Download a backup</button><button class="sec" id="saveWarnX" title="Hide">×</button>';document.body.appendChild(el);
    document.getElementById('saveWarnB').onclick=e=>{try{markExport();download('voxel-links-backup.json',JSON.stringify(careerDump()),'application/json',e.target)}catch(x){}};document.getElementById('saveWarnX').onclick=()=>{el.style.display='none'}}
  el.style.display=w?'flex':'none';document.body.classList.toggle('vsup',!!w);el.style.background=s.warn?TK('red600',.92):TK('g950',.92);const bt=document.getElementById('saveWarnB');bt.style.display=s.warn||s.roB?'':'none';bt.textContent=s.warn?'Download a backup':'Export';const t=document.getElementById('saveWarnT');if(t)t.textContent=w||'';
  if(s.warn&&!vsBanner.up){vsBanner.up=1;try{bt.focus()}catch(e){}}if(!s.warn)vsBanner.up=0}
/* R6.8 the tab lock: the tab holding voxellinks.lock writes the career and beats every LOCK_BEAT; another tab opens the career read-only and follows it on the storage event; a lock not beaten for LOCK_STALE, or this tab's own after a reload (sessionStorage keeps the tab's id), is taken over. In a browser the boot never decides: a long boot reads another tab's lock from a stale copy (Chromium refreshes a tab's localStorage view only between tasks), so the career opens read-only ('check') and lockLook decides after the boot has yielded, re-checking a stale or missing lock LOCK_BEAT + LOCK_SETTLE later and taking it only if it is still free, then confirming the write; nothing writes the career until it is decided. The lock is tab state: never through VS, a backup, the remote store or an export */
const LOCK_BEAT=5000,LOCK_STALE=15000,TAB_ID=(()=>{let t=null;try{t=sessionStorage.getItem('vl.tab')}catch(e){}if(!t){try{const a=new Uint32Array(2);crypto.getRandomValues(a);t=a[0].toString(36)+a[1].toString(36)}catch(e){t=Date.now().toString(36)}try{sessionStorage.setItem('vl.tab',t)}catch(e){}}return t})();
function lockBeat(){if(VL.ro(CAR_KEY)==='check')return false;if(LOCK.wl){if(LOCK.own)try{localStorage.setItem(LOCK_KEY,JSON.stringify({id:TAB_ID,t:Date.now()}))}catch(e){}return!!LOCK.own}let L=null,o=null;try{L=localStorage;o=JSON.parse(L.getItem(LOCK_KEY))}catch(e){}if(!L)return true;const now=Date.now(),mine=!o||o.id===TAB_ID||!(now-o.t<LOCK_STALE),was=VL.ro(CAR_KEY)==='tab';
  if(mine){try{L.setItem(LOCK_KEY,JSON.stringify({id:TAB_ID,t:now}))}catch(e){}if(was){delete K.ro[CAR_KEY];if(K.up){S.car=carLoad();roNote();if(S.mode==='title')refreshTitle()}}}else if(!VL.ro(CAR_KEY)){K.ro[CAR_KEY]='tab';if(K.up)roNote()}return mine}
/* the boot's lock (VL.boot's lock step): headless (no task queue) it decides at once, as before; in a browser it waits for lockLook (LOCK.async, LOCK.later: the checks set them) */
const LOCK_SETTLE=1000,LOCK_CONFIRM=250,LOCK={async:null,later:(f,ms)=>setTimeout(f,ms)},lockRead=()=>{try{return JSON.parse(localStorage.getItem(LOCK_KEY))}catch(e){return null}};
function lockBoot(){if(!(LOCK.async!=null?LOCK.async:REAL))return lockBeat();if(VL.ro(CAR_KEY))return false;K.ro[CAR_KEY]='check';if(!lockWeb())LOCK.later(lockLook,0);return false}
/* M3d: Web Locks where the browser has them (LOCK.wl). The tab granted 'voxellinks.tab' holds it for its lifetime and writes the career; another tab opens it read-only and queues for the lock, taking the career over (and re-reading stored state) when the holder closes. The holder still beats voxellinks.lock for older builds' tabs, and nothing in this build reads that lock while LOCK.wl. Without navigator.locks (the headless harness), or if the request is refused (an opaque origin), the beat lock below decides */
function lockWeb(){const L=LOCK.web!==undefined?LOCK.web:typeof navigator!=='undefined'&&navigator.locks,hold=()=>new Promise(()=>{});if(!L||typeof L.request!=='function')return false;
  try{L.request('voxellinks.tab',{ifAvailable:true},l=>{LOCK.wl=1;LOCK.own=!!l;lockSettle(!!l);if(l)return hold();L.request('voxellinks.tab',()=>{lockWon();return hold()}).catch(()=>{})}).catch(()=>{if(!LOCK.wl)LOCK.later(lockLook,0)})}catch(e){return false}return true}
function lockWon(){LOCK.own=1;if(VL.ro(CAR_KEY)==='tab')delete K.ro[CAR_KEY];lockBeat();RM.pend=1;remoteDone(0)}
function lockLook(){const o=lockRead();if(o&&o.id===TAB_ID)return lockTake();if(o&&Date.now()-o.t<LOCK_STALE)return lockSettle(false);LOCK.later(lockRecheck,(o?LOCK_BEAT:0)+LOCK_SETTLE)}
function lockRecheck(){const o=lockRead();if(o&&o.id!==TAB_ID&&Date.now()-o.t<LOCK_STALE)return lockSettle(false);lockTake()}
function lockTake(){try{localStorage.setItem(LOCK_KEY,JSON.stringify({id:TAB_ID,t:Date.now()}))}catch(e){}LOCK.later(()=>{const o=lockRead();lockSettle(!o||o.id===TAB_ID)},LOCK_CONFIRM)}
function lockSettle(mine){if(VL.ro(CAR_KEY)!=='check')return;delete K.ro[CAR_KEY];if(mine)lockBeat();else K.ro[CAR_KEY]='tab';S.car=carLoad();roNote();if(S.mode==='title'){refreshTitle();if(S.chTab==='pCareer')carPanel()}}
function lockFree(){try{const o=JSON.parse(localStorage.getItem(LOCK_KEY));if(o&&o.id===TAB_ID)localStorage.removeItem(LOCK_KEY)}catch(e){}}
/* a storage event from another tab: the lock went or changed hands, or the career changed under a read-only tab */
function lockStorage(e){if(!e||e.key===LOCK_KEY||e.key==null){lockBeat();return}if(e.key===CAR_KEY&&(VL.ro(CAR_KEY)==='tab'||VL.ro(CAR_KEY)==='check')){S.car=carLoad();if(S.mode==='title')refreshTitle()}}
function roNote(){const c=VL.ro(CAR_KEY),r=VL.ro('voxellinks.round');VS.note(c==='newer'?'Your career was saved by a newer build of Voxel Links. It is read-only here; export it to keep a copy.':c==='broken'?'This build could not bring your career up to date. It is kept exactly as it was and is read-only here; export it to keep a copy.':c==='tab'?'Your career is open in another tab. This tab shows it read-only and follows it.':r==='newer'?'A round saved by a newer build is kept for it. New rounds play here without saving for later.':r==='mode'?'A round of a kind this build does not have ('+K.roMode+') is kept for the build that saved it. New rounds play here without saving for later.':r==='broken'?'This build could not bring your saved round up to date. It is kept as it was; new rounds play here without saving for later.':null,c==='newer'||c==='broken'||r==='newer'||r==='mode'||r==='broken')}
/* a live swing is saved when it is committed and re-struck on resume: the same click, the same tick, so the same shot */
const swingSnap=k0=>({h:S.hi,n:(S.log[S.hi]||[]).length,c:curClub().id,shape:S.shape,traj:S.traj,yaw:S.yaw,pow:S.pow,acc:S.acc,mis:S.mis||0,k0:k0|0,pv:!!S.provNext});
function reswing(e){if(!W||!e)return;const ci=CLUBS.findIndex(c=>c.id===e.c);if(ci>=0){S.sg=false;S.club=ci}else{const si=SG_SET?SG_SET.findIndex(c=>c.id===e.c):-1;if(si>=0){S.sg=true;S.sgi=si}}
  S.shape=e.shape|0;S.traj=e.traj==null?1:e.traj;S.yaw=e.yaw;S.pow=e.pow;S.acc=e.acc;S.mis=e.mis||0;S.swingK0=e.k0|0;S.provNext=!!e.pv;S.autoAim=false;S.intro=null;S.swingSave=e;doStrike()}
/* F-160: the one conditions block, run once per play by VL.play (it was copied into careerEvent, tourEvent, cupSession, weeklyStart and t8Event): the course, its day and the seed box; the round-to-come's own parts (the old pending slots) go to the next play's cfg */
const COND_S=['seed','setup','season','wear','casual','kind','twist','islDay'],COND_P=['car','cup','xg','weekly','scen','hs','golfer','forceCv','recv','fmt','four'],islNow=()=>({forceCv:CVX,twist:0,fmt:{format:0,twist:0}});
function applyConditions(c){if(c.prep)islPrep(...c.prep);for(const k of COND_S)if(k in c)S[k]=c[k];if('box' in c&&typeof seedIn!=='undefined')seedIn.value=c.box;S.over=false;if('tour' in c)S.tourRound=c.tour;for(const k of COND_P)if(k in c)PEND[k]=c[k]}
/* the career's opponent for a round in its cfg: a v8 round names its partner (pid; a playoff bot's id carries the playoff), a v4 round finds it in the season */
function carResumeBot(C,R){if(R.v8){if(R.pid==null)return 0;const b=carBot(C,C.players[R.pid],R.e);return R.po?Object.assign({},b,{id:100+R.pid+1000*R.po}):b}const pid=isMajor(C.tier,R.e)?C.cur.major.partners[R.r]:C.cur.partners[R.e];return carBot(C,C.players[pid],R.e)}
/* Continue: the unfinished round resumes in the mode it was saved in. A mode's resume(save, c) gives the play's config: null when it cannot take the round now (it then resumes as casual, as every build has), false when it refuses (with its own note); a mode that names another (resume:'casual') resumes there; any other mode resumes as itself with the save's ghost and house player. A save of a mode this build does not have never reaches here (loadSave keeps it for the build that made it) */
function continueRound(){const sv=loadSave();if(!sv)return false;const id=sv.play&&sv.play.id||'casual',M=K.modes[id];if(!M)return false;const fn=typeof M.resume==='function';let to=typeof M.resume==='string'?M.resume:id;S.guardPass=true;
  try{const c={save:sv,n:sv.n,seed:sv.seed,box:sv.seed,tour:null};let x=fn?M.resume(sv,c):null;if(x===false)return false;if(!x){if(fn)to='casual';x=Object.assign(c,{ghost:sv.ghost,opp:sv.house})}VL.play(to,x)}finally{S.guardPass=false}return true}
/* the resumes of the modes that need more than the save's ghost (career, tour, the team cup); a career or a cup round waits while the career is read-only */
function resumeCareer(sv,c){if(carRO()){hint(carROText(),3);return false}if(!S.car)return null;const q=sv.play&&sv.play.cfg||{},car=q.car||sv.carRound;return Object.assign(c,{car},fsResume(S.car,car))}
function resumeTour(sv,c){if(!S.tour)return null;const T=S.tour,m=T.partners&&T.partners[sv.tourRound]!=null?fieldById(T,T.partners[sv.tourRound]):tourPartner(T);return Object.assign(c,{tour:sv.tourRound,opp:tierFor(m.skill,m.name,100+m.id)})}
function resumeCup(sv,c){if(carRO()){hint(carROText(),3);return false}if(!cupOpen(S.car))return null;const k=cupCfg(S.car);return Object.assign(c,{cup:k.cup,xg:k.xg,opp:sv.house})}
/* a new round over an unfinished one asks first: resume it, or start the new one and let the old one go */
let UI_T=-1e9;if(typeof addEventListener==='function'){addEventListener('pointerdown',()=>{UI_T=performance.now()},true);addEventListener('keydown',()=>{UI_T=performance.now()},true)}
const uiRecent=()=>typeof performance!=='undefined'&&performance.now()-UI_T<1500;
function newRoundGuard(go){const sv=loadSave();if(!sv||S.guardPass||S.bug||S.scenPending)return false;if(typeof document!=='undefined'&&document.body){let el=document.getElementById('guard');
    if(!el){el=document.createElement('div');el.id='guard';el.style.cssText='position:fixed;inset:0;z-index:70;display:flex;align-items:center;justify-content:center;background:color-mix(in srgb,var(--shade) 45%,transparent)';el.innerHTML='<div class="panel" style="max-width:420px;padding:16px 18px;border-radius:12px;background:var(--g950);color:var(--white);font:14px/1.4 system-ui,sans-serif"><b>You have an unfinished round</b><p id="guardT" style="opacity:.85;margin:6px 0 12px"></p><button id="guardR">Resume it</button> <button class="sec" id="guardN">Start the new round</button></div>';document.body.appendChild(el)}
    const pars=parsFor(sv.n,sv.cv|0,sv.kind),t=roundTotal(sv.log,pars,sv.cv|0),txt=document.getElementById('guardT');if(txt)txt.textContent='Course #'+sv.seed+' · '+sv.n+' holes · '+t.done+' done · '+relS(t.s-t.p)+'. Starting a new round lets it go.';el.style.display='flex';
    document.getElementById('guardR').onclick=()=>{el.style.display='none';continueRound()};document.getElementById('guardN').onclick=()=>{el.style.display='none';clearSave();if(go){S.guardPass=true;try{go()}finally{S.guardPass=false}}}}
  return true}
VL.feature({id:'s4.store',kind:'shell',deps:[],f:['S-4']});
