/* ===== M5 · People: clip links (F-075), names and keys (F-077), the weekly (F-076), hot-seat (F-072), career export (F-078), the guide (F-079), club cards (F-074) ===== */
const u8s=s=>new TextEncoder().encode(s),s8=b=>new TextDecoder().decode(b),b64u=b=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')},
  ub64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),nEnc=s=>b64u(u8s(s)),nDec=s=>{try{return s8(ub64(s||''))}catch(e){return''}},linkOf=c=>location.href.split('#')[0]+'#'+c;
function linkBox(h,p,code,link=true){$('linkH').textContent=h;$('linkP').textContent=p;$('linkCode').value=link?linkOf(code):code;$('linkOv').classList.remove('hide');$('linkCopy').onclick=e=>copyText($('linkCode').value,e.target);$('linkClose').onclick=()=>$('linkOv').classList.add('hide')}
/* F-077: a key per browser, a name that belongs to whoever signed with it first; no account */
const NAME_MAX=16,NAME_RE=/^[\p{L}\p{N} -]{1,16}$/u,SIG={name:'ECDSA',namedCurve:'P-256'},SIGH={name:'ECDSA',hash:'SHA-256'},keyGet=()=>lsGet('voxellinks.key',null),subtle=()=>globalThis.crypto&&crypto.subtle;
async function keyMake(name){name=(name||'').trim();if(!NAME_RE.test(name))throw new Error('Letters, digits, spaces and hyphens, up to '+NAME_MAX);if(!subtle())throw new Error('This browser has no WebCrypto');
  const k=await subtle().generateKey(SIG,true,['sign','verify']),o={name,pub:b64u(new Uint8Array(await subtle().exportKey('raw',k.publicKey))),jwk:await subtle().exportKey('jwk',k.privateKey)};lsSet('voxellinks.key',o);return o}
async function signCode(code){code=code.split('.')[0];const K=keyGet();if(!K||!subtle())return code;const pk=await subtle().importKey('jwk',K.jwk,SIG,false,['sign']);return code+'.'+nEnc(K.name)+'.'+K.pub+'.'+b64u(new Uint8Array(await subtle().sign(SIGH,pk,u8s(code+'|'+K.name))))}
async function sigCheck(str){const[code,n,pub,sig]=(str||'').trim().replace(/^.*#/,'').split('.'),name=nDec(n);if(!sig)return{code,signed:false,ok:false};
  try{const k=await subtle().importKey('raw',ub64(pub),SIG,false,['verify']);return{code,name,pub,signed:true,ok:NAME_RE.test(name)&&await subtle().verify(SIGH,k,ub64(sig),u8s(code+'|'+name))}}catch(e){return{code,name,pub,signed:true,ok:false}}}
/* F-075: a shot is a link — its inputs, re-simulated on the friend's machine, so the clip is also proof */
const CLIP_V=1,CLIP_ADDRESS=.9,CLIP_CARD_T=.8,CLIP_TOL=.05;
function clipFrom(L,h,k,hd,seed,n,cv){const e=L&&L[k];if(!e||e.kind!==0||cv<4)return null;const T=holeTally(L,hd.seat|0,cv),P=holePath(L,{x:0,z:0},hd.seat|0,cv),o=P[k];let base=o.start,d=null;
  if(o.lf===2)for(let j=k-1;j>=0;j--)if(L[j].kind===3){base=P[j].start;d=[L[j].dx,L[j].dz];break}
  return{seed,n,cv,hdr:hdrOf(hd),h,sn:T[k].no,mu:T[k].att>=MULL_ATTEMPT,base,d,sx:o.start[0],sz:o.start[1],plug:!!o.plug,lf:d?2:o.lf===2?0:o.lf|0,e,r:e.r,ex:o.end[0],ez:o.end[1]}}
function clipEncode(o,name){const w=new BW(),H=o.hdr,e=o.e,P=(x,z)=>{w.w(qPos(x),16);w.w(qPos(z),16)};const V2=o.cv>=CV_ISL;w.w(V2?CLIP_V2:CLIP_V,4);w.w(o.seed,30);w.w(V2&&o.n===1?3:HOLESC.indexOf(o.n),2);w.w(o.cv,V2?5:3);w.w(bagMask(H.bag),22);w.w(H.ball,1);w.w(H.setup,2);w.w(H.season,2);w.w(H.wear,2);w.w(V2?H.kind&7:H.kind,V2?3:1);if(V2&&(H.kind&7)===6)w.w(H.kind>>3,6);w.w(H.meter,2);w.w(H.seat,2);w.w(H.look>>>0,24);if(V2)w.w(clamp(H.islDay|0,0,65535),16);
  w.w(o.h,5);w.w(Math.min(o.sn,63),6);w.w(o.mu?1:0,1);P(o.base[0],o.base[1]);w.w(o.plug?1:0,1);w.w(o.lf,2);if(o.lf===2){w.w(o.d[0]+15,5);w.w(o.d[1]+15,5)}
  w.w(e.c,5);w.w(e.s,3);w.w(e.t,3);w.w(e.y,16);w.w(e.p,8);w.w(e.a,8);w.w((e.m|0)+7,4);w.w(e.k||0,11);w.w(e.r,3);P(o.ex,o.ez);return'K'+w.str()+(name?'.'+nEnc(name.slice(0,NAME_MAX)):'')}
function clipDecode(str){try{const[body,nm]=(str||'').trim().replace(/^.*#/,'').split('.');if(body[0]!=='K')return null;const r=new BR(body.slice(1));const V=r.r(4);if(V!==CLIP_V&&V!==CLIP_V2)return null;const V2=V===CLIP_V2;
    const o={seed:r.r(30)};{const ni=r.r(2);o.n=V2&&ni===3?1:HOLESC[ni]}o.cv=r.r(V2?5:3);o.hdr={bag:maskBag(r.r(22)),ball:r.r(1),setup:r.r(2),season:r.r(2),wear:r.r(2)};{let k=r.r(V2?3:1);if(V2&&k===6)k|=r.r(6)<<3;o.hdr.kind=k}Object.assign(o.hdr,{meter:r.r(2),seat:r.r(2),look:r.r(24),casual:0});if(V2)o.hdr.islDay=r.r(16);
    o.h=r.r(5);o.sn=r.r(6);o.mu=!!r.r(1);let x=uPos(r.r(16)),z=uPos(r.r(16));o.plug=!!r.r(1);o.lf=r.r(2);if(o.lf===2){x+=(r.r(5)-15)/100;z+=(r.r(5)-15)/100}o.sx=x;o.sz=z;
    const e=o.e={kind:0,c:r.r(5),s:r.r(3),t:r.r(3),y:r.r(16),p:r.r(8),a:r.r(8),m:r.r(4)-7,k:r.r(11),r:r.r(3)};o.r=e.r;o.ex=uPos(r.r(16));o.ez=uPos(r.r(16));
    if(!o.n||o.seed<1||o.cv<4||o.cv>(V2?CVX:CV)||V2&&o.cv<CV_ISL||o.h>=o.n||o.sn<1||e.c>=CLUB_SET.length||e.t>=TRAJ.length||e.s>4||e.r>3)return null;o.name=nDec(nm).slice(0,NAME_MAX);return o}catch(e){return null}}
function clipShare(o){if(!o)return;const K=keyGet(),code=clipEncode(o,K?K.name:'');linkBox('Clip link','Whoever opens it watches this shot re-simulated from its inputs, then plays the course or takes on the shot · '+code.length+' characters',code)}
function clipPlay(o){const H=o.hdr;useCalib(o.cv);$('clipOv').classList.add('hide');$('linkOv').classList.add('hide');
  Object.assign(S,{seed:o.seed,n:o.n,cv:o.cv,pars:parsFor(o.n,o.cv,H.kind),log:Array.from({length:o.n},()=>[]),strokes:new Array(o.n).fill(null),setup:H.setup,season:H.season,wear:H.wear,casual:0,kind:H.kind,seat:H.seat,ball:H.ball,look:H.look,meter:H.meter,ghost:null,match:null,hs:null,xg:null,lab:null,scen:null,range:null,tourRound:null,carRound:null,cup:null,guide:null,hinfo:{},over:false,skip:false});setBag(H.bag);if(o.cv>=CV_ISL){S.islDay=H.islDay|0;islRoundStart()}
  $('title').classList.add('hide');$('card').classList.add('hide');$('hud').classList.add('on');$('tools').classList.add('on');$('bottom').classList.remove('on');$('ghostT').style.display='none';$('matchT').style.display='none';AU.init();
  S.replay={clip:o,hi:o.h,who:o.name||'A friend',name:(o.name||'A friend')+'\u2019s'};loadHole(o.h,true);B=PB;place(o.sx,o.sz);PB.sx=o.sx;PB.sz=o.sz;PB.plug=o.plug;PB.lf=o.lf;const e=o.e,c=clubById(e.c);selectClubId(e.c);S.shape=e.s;S.traj=e.t;S.yaw=uYaw(e.y);S.stroke=o.sn-1;snapCam();
  const seed=shotSeed(o.seed,o.h,o.sn,o.mu?MULL_ATTEMPT+H.seat:H.seat?SEAT_ATTEMPT+H.seat:0),pre=preSim(c,uPow(e.p),uAcc(e.a),uYaw(e.y),e.s,e.t,seed,e.k,o.plug,o.lf,uMis(e.m));
  msg(esc(S.replay.name)+' shot','Course #'+o.seed+' · hole '+(o.h+1)+' · '+c.n+' · '+Math.round(MM.hyp(W.pin.x-o.sx,W.pin.z-o.sz))+' m to the pin',2.4);updateHud(true);
  S.mode='wait';S.wait=CLIP_ADDRESS;S.next=()=>beginSwing({pow:uPow(e.p),onContact:()=>{B=PB;PB.rng=mulberry32(seed);PB.k0=e.k;PB.ballType=H.ball;PB.plug=o.plug;PB.lf=o.lf;strike(c,uPow(e.p),uAcc(e.a),uYaw(e.y),e.s,e.t,uMis(e.m));S.mode='shot';S.ff=1;S.shotEnd=S.t;S.shotCam=Object.assign(shotCamFor(pre,c),{follow:true,t0:S.t});AU.play(c.putter?'putt':'hit',.8)}})}
function clipEnd(){const o=S.replay.clip,C=S.shotCam,r=resCode(B.st),d=MM.hyp(W.pin.x-B.x,W.pin.z-B.z);if(r===1){AU.play('cup');S.holedT=S.t}else if(r===2)AU.play('splash');
  o.ok=r===o.r&&(r!==0||MM.hyp(B.x-o.ex,B.z-o.ez)<=CLIP_TOL);o.got=[B.x,B.z];o.fin=r===1?'holed':r===2?'in the water':r===3?'out of bounds':(d<10?d.toFixed(1):Math.round(d))+' m from the pin';
  const rev=C&&C.rev&&r===0;if(rev)S.rev=2;S.wait=rev?CAM3.rev:CLIP_CARD_T;S.mode='wait';S.next=()=>{S.rev=null;if(!reelNext())clipCard()}}
function clipCard(){const o=S.replay.clip;S.mode='result';S.over=true;$('clipBody').innerHTML='<h1 style="font-size:30px">'+esc(S.replay.name)+' shot</h1><p class="sub">Course #'+o.seed+' · '+BIOMES[biomeOf(o.seed,o.cv)].n+' · hole '+(o.h+1)+' · '+clubById(o.e.c).n+' · finished '+o.fin+'</p><p class="sub" style="font-size:13px">'+(o.ok?'✓ re-simulated here from its inputs: the same shot':ic('warn')+' this build plays it differently')+(o.hdr.meter?' · slow meter':'')+'</p>';$('clipOv').classList.remove('hide');
  $('clipAgain').onclick=()=>clipPlay(o);$('clipCourse').onclick=()=>{clipExit();seedIn.value=o.seed;showBiome();go(o.n,null,o.hdr.kind)};$('clipChal').onclick=()=>clipChal(o);$('clipMenu').onclick=clipExit}
function clipExit(){$('clipOv').classList.add('hide');S.replay=null;S.over=false;$('btnMenu').onclick()}
function clipChal(o){clipExit();const H=o.hdr;S.seed=o.seed;seedIn.value=o.seed;S.mode='title';labStart({seed:o.seed,n:o.n,cv:o.cv,bag:H.bag,ball:H.ball,setup:H.setup,season:H.season,wear:H.wear,kind:H.kind,hole:o.h,stroke:o.sn,sx:o.sx,sz:o.sz,ex:o.ex,ez:o.ez,holed:o.r===1,plug:o.plug,lf:o.lf,club:o.e.c},'title')}
/* the stats panel's best shots, each a clip */
function bestShots(A){const out=[];A.forEach(R=>{if(R.code&&R.hk)R.rows.forEach((r,i)=>R.hk[i]&&out.push({R,r,hk:R.hk[i],sg:col(r,'sg')}))});return out.sort((a,b)=>b.sg-a.sg).slice(0,6)}
function bestShotsHtml(A){const L=bestShots(A);return L.length?'<div class="sub" style="text-align:left;font-size:13px;color:var(--ink)"><b>Best shots</b>'+L.map((x,i)=>{const r=x.r,c=CLUB_SET[col(r,'club')];return'<div class="sotr">Course #'+col(r,'seed')+' · hole '+col(r,'hole')+' · '+(c?c.s:'')+' · '+col(r,'d0')+' m → '+(col(r,'result')===1?'holed':col(r,'d1')+' m')+' · '+sgS(x.sg)+' <button class="sec" data-sw="'+i+'"><svg class="ic" aria-hidden="true"><use href="#i-play"/></svg> Watch</button> <button class="sec" data-sc="'+i+'"><svg class="ic" aria-hidden="true"><use href="#i-link"/></svg> Clip</button></div>'}).join('')+'</div>':''}
function bestShotsBind(el,A){const L=bestShots(A);el.querySelectorAll('[data-sw]').forEach(b=>b.onclick=()=>{const x=L[+b.dataset.sw];watchCode(x.R.code,x.hk[0],x.hk[1],'pStats')});
  el.querySelectorAll('[data-sc]').forEach(b=>b.onclick=()=>{const x=L[+b.dataset.sc],d=decodeRound(x.R.code);if(d)clipShare(clipFrom(d.log[x.hk[0]],x.hk[0],x.hk[1],d,d.seed,d.n,d.cv))})}
/* every link lands here: rounds (signed or not), challenges, scenarios, clips, hot-seat bundles, club cards */
function linkOpen(c,boot){c=(c||'').trim().replace(/^.*#/,'');if(!c)return false;if(/^VLBUG[01]\./.test(c)){bugOpen(c).then(ok=>{if(!ok)$('ghostIn').placeholder='That bug code did not decode'});return true}if(boot)S.fromLink=1;$('bannerX').innerHTML='';$('btnGhost').style.display='';const t=c[0];
  if(/^R1!/.test(c))return reelOpen(c);if(t==='K'){S.reelLink=null;const o=clipDecode(c);if(o){clipPlay(o);return true}return false}
  if(/^I1!/.test(c))return islBanner(c);if(/^H1!/.test(c))return hsBanner(c);if(/^L1!/.test(c))return clubLoad(c);
  if(t==='S'&&scenDecode(c)){chTab('pGhosts');return scenBanner(c)}
  if(t==='V'&&ghostInfo(c)||t==='C'&&chalInfo(c)){chTab('pGhosts');setGhostBanner(c);return true}return false}
/* idle-time verification in the clubhouse: one hole per slice, the scene untouched (club cards, the weekly's ghosts) */
const VQ={q:[],on:false,cache:new Map(),w:null,n:0,wait:{},idle:0},VQ_HOLES=18,VQ_IDLE=30e3;
/* where the browser allows it, a worker built from this page's own script verifies whole rounds off the main thread; otherwise one hole per idle slice */
function vqWorker(){if(VQ.w!==null)return VQ.w;VQ.w=false;try{if(typeof Worker!=='function')return false;const js=[...document.querySelectorAll('script')].map(x=>x.textContent).find(t=>t.includes('function vqWorker'));if(!js)return false;
  const stub="const gl=new Proxy({},{get:(t,k)=>k==='getContext'?()=>gl:k==='getExtension'?()=>null:k==='createImageData'?(w,h)=>({data:new Uint8ClampedArray(w*h*4)}):k==='getShaderParameter'||k==='getProgramParameter'?()=>true:k==='getActiveUniform'?()=>({name:'u'}):/^create/.test(k)?()=>({}):/^[A-Z_0-9]+$/.test(k)?1:()=>0}),el=()=>new Proxy({style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},children:[],dataset:{},value:'1',textContent:'',innerHTML:'',addEventListener(){},querySelector:()=>el(),querySelectorAll:()=>[],appendChild(){},insertAdjacentHTML(){},getContext:()=>gl,closest:()=>el(),focus(){},select(){},setPointerCapture(){}},{get:(t,k)=>k in t?t[k]:(t[k]=typeof k==='string'&&k.startsWith('on')?null:undefined)});";
  const body="(function(document,window,addEventListener,innerWidth,innerHeight,devicePixelRatio,localStorage,location,navigator,requestAnimationFrame){"+js+"\nself.onmessage=e=>{let res;try{const d=decodeRound(e.data.code);if(!d||d.cv<4)throw new Error('does not decode');useCalib(d.cv);setBag(d.bag);const r=verifyRound6(d);res=r.ok?{ok:true,total:r.total,par:r.par,rel:r.rel}:{ok:false,why:r.why}}catch(x){res={ok:false,why:String(x&&x.message||x)}}postMessage({id:e.data.id,res})}})({getElementById:()=>el(),createElement:()=>el(),body:el(),querySelectorAll:()=>[],querySelector:()=>el()},{},()=>{},800,600,1,{getItem:()=>null,setItem(){},removeItem(){},key:()=>null,length:0},{hash:'',href:''},{},()=>0)";
  const w=new Worker(URL.createObjectURL(new Blob([stub+body],{type:'text/javascript'})));
  w.onmessage=e=>{const j=VQ.wait[e.data.id];delete VQ.wait[e.data.id];if(j){const r=e.data.res;if(r.ok)r.d=decodeRound(j.code);VQ.done=(VQ.done||0)+1;try{j.cb(r)}catch(x){}}if(!Object.keys(VQ.wait).length)VQ.idle=setTimeout(()=>{w.terminate();VQ.w=null},VQ_IDLE)};
  w.onerror=()=>{VQ.w=false;const P=Object.values(VQ.wait);VQ.wait={};P.forEach(j=>vqAdd(j.code,j.cb))};return VQ.w=w}catch(e){return false}}
function vqAdd(code,cb){const w=vqWorker();if(w){clearTimeout(VQ.idle);const id=++VQ.n;VQ.wait[id]={code,cb};w.postMessage({id,code});return}VQ.q.push({code,cb,h:0,holes:[]});if(!VQ.on){VQ.on=true;vqNext()}}
function vqStep(){const j=VQ.q[0];if(!j){VQ.on=false;VQ.cache.clear();return}if(S.mode!=='title'){setTimeout(vqStep,500);return}const W0=W,cv0=S.cv,t0=performance.now();let res=null;
  try{if(!j.d){j.d=decodeRound(j.code);if(!j.d||j.d.cv<4)throw new Error('does not decode');j.pars=parsFor(j.d.n,j.d.cv,j.d.kind)}const d=j.d;useCalib(d.cv);const key=[d.seed,j.h,d.cv,d.kind,d.setup,d.season,d.wear,d.twist|0].join('/');W=VQ.cache.get(key);if(!W){W=genHole(d.seed,j.h,j.pars[j.h],d.cv,d.setup,d);VQ.cache.set(key,W);if(VQ.cache.size>VQ_HOLES)VQ.cache.delete(VQ.cache.keys().next().value)}if(W.marks)W.marks.length=0;const R=holeReplay(d.log[j.h]||[],j.h,d);if(!R.ok)throw new Error(R.why);j.holes.push(holeTally(d.log[j.h]||[],d.seat,d.cv).n);
    if(++j.h>=d.n){for(let s=0;s<d.n;s+=9)if(mullCount(d.log,s,Math.min(d.n,s+9))>MULL_PER_NINE)throw new Error('mulligans');const total=j.holes.reduce((a,b)=>a+b,0),par=j.pars.reduce((a,b)=>a+b,0);res={ok:true,total,par,rel:total-par,d}}}
  catch(e){res={ok:false,why:String(e&&e.message||e)}}finally{W=W0;useCalib(cv0)}VQ.slice=Math.max(VQ.slice||0,performance.now()-t0);
  if(res){VQ.q.shift();try{j.cb(res)}catch(e){}}vqNext()}
const vqNext=()=>(window.requestIdleCallback||(f=>setTimeout(f,16)))(vqStep);
/* F-076: one 18-hole seed for everyone all week, one attempt; the server re-simulates, the ghosts re-verify here; no endpoint → a local personal best */
const WEEKLY_SETUP=2,WEEKLY_WEAR=2,TOP_N=10,WK={seed:0,list:null,busy:false};
function isoWeek(dt=new Date()){const t=new Date(Date.UTC(dt.getFullYear(),dt.getMonth(),dt.getDate())),day=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-day);const y=t.getUTCFullYear(),w=Math.ceil(((t-Date.UTC(y,0,1))/864e5+1)/7);return{y,w,seed:y*100+w}}
const wkGet=()=>{const v=lsGet('voxellinks.weekly',null);return v&&v.hist?v:{hist:{},cur:null}},wkRedraw=()=>{if(S.mode==='title'&&S.chTab==='pFriends')friendsPanel()};
function wkFetch(){const wk=isoWeek(),lb=lbUrl();if(!lb||WK.busy||WK.seed===wk.seed&&WK.list||typeof fetch!=='function')return;WK.busy=true;
  fetch(lb+'/api/weekly/'+wk.seed+'/top').then(r=>r.json()).then(j=>{WK.seed=wk.seed;WK.list=(j.rounds||[]).slice(0,TOP_N).map(x=>({name:String(x.name||'').slice(0,NAME_MAX),code:String(x.code||''),total:x.total,ok:null}));
    WK.list.forEach(g=>vqAdd(g.code.split('.')[0],r=>{g.ok=r.ok&&r.d.seed===wk.seed&&r.d.n===18;wkRedraw()}))}).catch(()=>{WK.seed=wk.seed;WK.list=[]}).finally(()=>{WK.busy=false;wkRedraw()})}
function weeklyGhosts(){return(WK.list||[]).filter(g=>g.ok).map((g,i)=>{const d=decodeRound(g.code);return{name:g.name,col:i?[.55,.75,1]:[1,.82,.35],ball:newBall(),L:d.log,steps:[],k:0,seat:d.seat,ballType:d.ball}})}
function weeklyStart(){const wk=isoWeek(),st=wkGet();if(st.hist[wk.seed]||st.cur===wk.seed)return;st.cur=wk.seed;lsSet('voxellinks.weekly',st);seedIn.value=wk.seed;S.seed=wk.seed;S.over=false;S.setup=WEEKLY_SETUP;S.season=courseSeason(wk.seed);S.wear=WEEKLY_WEAR;S.casual=0;S.kind=0;S.tourRound=null;S.weeklyPending=wk.seed;S.xgPending=weeklyGhosts();startRound(18,null,null,0)}
function weeklyFinish(code,s,rel){const st=wkGet();st.hist[S.weekly]={s,rel,code,t:Date.now(),meter:S.meter|0};st.cur=null;lsSet('voxellinks.weekly',st);if(lbUrl()&&keyGet())weeklyPost(S.weekly)}
async function weeklyPost(seed){const st=wkGet(),m=st.hist[seed],el=()=>$('wkPost');if(!m||m.posted)return;if(el())el().textContent='Posting to the leaderboard…';
  try{const code=await signCode(m.code),r=await fetch(lbUrl()+'/api/rounds',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,week:seed})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'the leaderboard said '+r.status);
    m.posted=1;m.rank=j.rank;m.of=j.of;lsSet('voxellinks.weekly',st);if(el())el().textContent='Verified by the server · '+ordn(j.rank)+' of '+j.of}catch(e){if(el())el().textContent=String(e&&e.message||e)}}
function weeklyCardHtml(){const m=wkGet().hist[S.weekly];if(!m)return'';const lb=lbUrl(),K=keyGet(),pb=Object.values(wkGet().hist).reduce((a,x)=>Math.min(a,x.rel),99);
  return'<div class="sub" style="font-size:16px">The weekly · week '+(S.weekly%100)+' · '+relS(m.rel)+' ('+m.s+')'+(m.meter?' · slow meter':'')+'</div><div id="wkPost" class="sub">'+(!lb?'Local personal best '+relS(pb)+' (no leaderboard set in Settings)':K?(m.posted?'Verified by the server · '+ordn(m.rank)+' of '+m.of:'Posting to the leaderboard…'):'Pick a name to post it: <input id="wkName" maxlength="16" style="width:130px"> <button class="sec" id="wkGo">Post</button>')+'</div>'}
function weeklyCardBind(){const b=$('wkGo');if(b)b.onclick=()=>keyMake($('wkName').value).then(()=>{$('wkPost').textContent='Posting…';weeklyPost(S.weekly)}).catch(e=>{$('wkPost').textContent=e.message});else if(lbUrl()&&keyGet())weeklyPost(S.weekly)}
/* F-072: two to four people on one laptop — honours on the tee, farthest from the hole next, one v6 record per seat */
const HS_SEATS=[2,4],PASS_T=1.2,HS_BALLS=[0,2,5,3,4];
const hsRows=()=>lsGet('voxellinks.hotseat',null)||[{name:(keyGet()||{}).name||'You',hcp:'',ball:0},{name:'',hcp:'',ball:2},{name:'',hcp:'',ball:5},{name:'',hcp:'',ball:3}];
function hsStart(n,rows){rows=rows||[...document.querySelectorAll('.hsrow')].map(r=>({name:r.querySelector('.hsn').value.trim().slice(0,12),hcp:r.querySelector('.hsh').value.trim(),ball:+r.dataset.ball||0}));lsSet('voxellinks.hotseat',rows);const P=rows.filter(p=>p.name);
  if(P.length<HS_SEATS[0]){$('hsMsg').textContent='Two names at least';return false}const me=myIndex()??myHandicap()??0;
  S.hsPending={P:P.map((p,i)=>({name:p.name,hcp:p.hcp===''?(i?0:me):clamp(+p.hcp||0,0,36),seat:i,look:lookSet(i?houseLook(7000+i):myLook(),'ball',p.ball),log:[],strokes:new Array(n).fill(null)})),cur:0,order:P.map((_,i)=>i)};
  S.seed=Math.max(1,(+seedIn.value|0)||1);seedIn.value=S.seed;S.over=false;S.setup=setupFor(S.seed);S.season=S.seasonPick>=0?S.seasonPick:courseSeason(S.seed);S.wear=S.seed===daily()?WEAR_LEVEL.daily:S.condPick|0;S.casual=1;S.kind=0;S.tourRound=null;startRound(n,null,null,0)}
function hsBall(p){const L=p.log[S.hi]||[],H=S.hs;if(!L.length)return{x:0,z:0,tee:true,n:0};const P=holePath(L,W.pin,p.seat),T=P.T,full=H.watch&&H.watch[H.P.indexOf(p)][S.hi];return{x:P.pos[0],z:P.pos[1],n:T.n,done:T.holed||T.n>=capFor(W.par,W.cv)||!!full&&L.length>=full.length}}
function hsNext(){const H=S.hs;let best=-1,bd=-1;for(const i of H.order){const b=hsBall(H.P[i]);if(b.done)continue;if(b.tee)return i;const d=MM.hyp(b.x-W.pin.x,b.z-W.pin.z);if(d>bd){bd=d;best=i}}return best}
function hsLoad(i){const H=S.hs,p=H.P[i];if(H.cur!==i)H.prev=H.cur;H.cur=i;S.log=p.log;S.strokes=p.strokes;S.seat=p.seat;S.look=p.look;const L=S.log[S.hi]||(S.log[S.hi]=[]);B=PB;if(L.length)syncBall();else{place(0,0);S.stroke=0}
  S.shape=0;S.traj=1;S.sg=false;S.mode='aim';S.ph=0;S.mark=0;S.lostShown=false;S.autoAim=true;autoClub();aimPin();cutTo(snapCam);buildClubs();updateHud(true)}
function hsHole(i){const H=S.hs;H.P.forEach(p=>{if(!p.log[i])p.log[i]=[]});if(i>0&&H.P.every(p=>!p.log[i].length)){const pv=p=>p.strokes[i-1]??99;H.order=H.order.slice().sort((a,b)=>pv(H.P[a])-pv(H.P[b]))}H.prev=null;const j=hsNext();hsLoad(j<0?H.order[0]:j);hsPass()}
function hsTurn(){const H=S.hs,j=hsNext();H.mullOK=H.cur;if(j>=0&&j!==H.cur){hsLoad(j);hsPass()}}
function hsHoled(){const j=hsNext();if(j<0)return false;hsLoad(j);hsPass();return true}
function hsCanMull(){const H=S.hs;if(H.prev==null||H.prev===H.cur||!S.casual||H.watch)return false;const P=H.P[H.prev],L=P.log[S.hi],e=L&&L[L.length-1],n0=S.hi<9?0:9;return!!e&&e.kind===0&&!e.mu&&!e.pv&&e.r!==1&&mullCount(P.log,n0,Math.min(S.n,n0+9))<MULL_PER_NINE}
function hsPass(){const H=S.hs,p=H.P[H.cur],b=hsBall(p),c=LOOK.ball[lookGet(p.look,'ball')],el=$('pass');
  el.innerHTML='<div style="border-color:rgb('+c.map(v=>v*255|0)+')"><b>'+esc(p.name)+' to play</b><small>'+(b.tee?'from the tee':Math.round(MM.hyp(W.pin.x-b.x,W.pin.z-b.z))+' m')+' · '+ordn(b.n+1)+' shot</small>'+(hsCanMull()?'<button class="sec" id="passMull">Mulligan for '+esc(H.P[H.prev].name)+'</button>':'')+'</div>';el.classList.remove('hide');S.passT=S.t+PASS_T;
  const m=$('passMull');if(m)m.onclick=e=>{e.stopPropagation();hsPassEnd();hsLoad(H.prev);takeMull()}}
function hsPassEnd(){$('pass').classList.add('hide');S.passT=0}
function hsDraw(){const H=S.hs;H.P.forEach((p,i)=>{if(i===H.cur)return;const b=hsBall(p);if(b.done)return;terrainAt(W,b.x,b.z);draw(ballMesh,M4.trs(b.x,TQ.h+BALL_R,b.z,BALL_R),ballOv(p.look));if(MM.hyp(b.x-PB.x,b.z-PB.z)>1.5)drawGolfer(b.x,b.z,MM.atan2(W.pin.x-b.x,W.pin.z-b.z),0,0,null,p.look)})}
function hsNetK(p){const sl=S.cv>=4&&S.n>=9?rate9(S.seed,0,S.pars,S.setup|0,S.season|0,S.wear|0,S.cv).slope/113:1;return Math.round(p.hcp*sl*S.n/9)}
function hsMatch(){const H=S.hs;if(H.P.length!==2)return null;const[a,b]=H.P,si=strokeIndex(S.seed,S.pars,S.cv),diff=clamp(Math.abs(hsNetK(a)-hsNetK(b)),0,2*S.n),rc=a.hcp>b.hcp?0:1,given=new Array(S.n).fill(0);for(let k=0;k<diff;k++){const h=si.indexOf(k%S.n+1);if(h>=0)given[h]++}
  let up=0,rem=S.n,dec=null;for(let h=0;h<S.n;h++){const x=a.strokes[h],y=b.strokes[h];if(x==null||y==null)continue;rem--;if(dec)continue;const nx=x-(rc?0:given[h]),ny=y-(rc?given[h]:0);up+=nx<ny?1:nx>ny?-1:0;if(Math.abs(up)>rem||!rem)dec={up,rem}}
  return{up,rem,dec,given,rc,text:up===0?(dec?'Match halved':'All square'):esc((up>0?a:b).name)+(dec?' wins '+(dec.rem?Math.abs(dec.up)+'&'+dec.rem:Math.abs(up)+' up'):' '+Math.abs(up)+' up')}}
function hsTot(p){let s=0,par=0;p.strokes.forEach((v,h)=>{if(v!=null){s+=v;par+=S.pars[h]}});return{s,par}}
function hsHud(){const H=S.hs,m=hsMatch(),k=H.P.map((p,i)=>{const t=hsTot(p),c=LOOK.ball[lookGet(p.look,'ball')];return'<i style="font-style:normal;color:rgb('+c.map(v=>v*255|0)+')">●</i> '+(i===H.cur?'<strong>':'')+esc(p.name)+' '+relS(t.s-t.par)+(i===H.cur?'</strong>':'')}).join('<br>')+(m?'<br>'+m.text:'');if(k!==H.hudK){H.hudK=k;$('hsT').innerHTML=k;$('hsT').style.display='block'}}
function hsCard(watch){const H=S.hs,m=hsMatch();clearSave();const codes=H.P.map(p=>encodeRound6(S.seed,S.n,p.log,Math.round(p.hcp),S.cv,{seat:p.seat,look:p.look,ball:p.ball!=null?p.ball:S.ball}));
  if(!watch&&!S.histDone){S.histDone=true;const o=H.P[0],cz={mull:0,gim:0};o.log.forEach(L=>(L||[]).forEach(e=>{if(e.mu)cz.mull++;if(e.kind===2)cz.gim++}));if(!cz.mull&&!cz.gim){const sv=[S.log,S.seat,S.look];S.log=o.log;S.seat=0;S.look=o.look;S.bookNews=bookAdd(codes[0],roundStats(o.log));shotsStore(shotRows(),codes[0]);[S.log,S.seat,S.look]=sv}}
  let h='<table><tr><th>Hole</th>'+S.pars.map((_,i)=>'<th>'+(i+1)+'</th>').join('')+'<th>Tot</th>'+(m?'':'<th>Net</th>')+'</tr><tr><th>Par</th>'+S.pars.map(x=>'<td>'+x+'</td>').join('')+'<td>'+S.pars.reduce((a,b)=>a+b,0)+'</td>'+(m?'':'<td></td>')+'</tr>';
  H.P.forEach((p,i)=>{const t=hsTot(p);h+='<tr><th>'+esc(p.name)+'</th>'+p.strokes.map((x,j)=>'<td class="'+(x==null?'':relC(x-S.pars[j]))+'">'+(x??'')+(m&&m.given[j]&&m.rc===i?'•':'')+'</td>').join('')+'<td><b>'+t.s+'</b></td>'+(m?'':'<td>'+(t.s-hsNetK(p))+'</td>')+'</tr>'});
  h+='</table><div class="sub" style="font-size:20px">'+(m?m.text:'Net: '+H.P.map(p=>({p,n:hsTot(p).s-hsNetK(p)})).sort((a,b)=>a.n-b.n).map((x,i)=>(i+1)+'. '+esc(x.p.name)+' '+x.n).join(' · '))+'</div><div class="sub">Course #'+S.seed+' · '+BIOMES[biomeOf(S.seed,S.cv)].n+' · '+(S.casual?'casual rules':'strict rules')+(m?' · • marks a handicap stroke':'')+'</div>';
  h+='<div class="row"><button class="big" id="hsShare">Share the round</button></div>';$('cardBody').innerHTML=h;
  ['btnShare','btnLab','btnVs'].forEach(id=>$(id).classList.add('hide'));$('hsShare').onclick=()=>linkBox('Hot-seat round','Everyone’s round in one link: a friend plays against any one of you, or watches the whole round',hsEncode(codes));$('shareBox').classList.add('hide');$('card').classList.remove('hide');S.over=true;S.mode='result'}
const hsEncode=codes=>'H1!'+S.hs.P.map((p,i)=>nEnc(p.name)+'~'+codes[i]).join('!');
function hsDecode(t){const p=(t||'').trim().replace(/^.*#/,'').split('!');if(p[0]!=='H1')return null;const P=p.slice(1).map(x=>{const i=x.indexOf('~');return{name:nDec(x.slice(0,i)).slice(0,12)||'Player',code:x.slice(i+1),d:decodeRound(x.slice(i+1))}});
  return P.length>=HS_SEATS[0]&&P.length<=HS_SEATS[1]&&P.every(q=>q.d&&q.d.cv>=4&&q.d.seed===P[0].d.seed&&q.d.n===P[0].d.n&&q.d.kind===P[0].d.kind)?P:null}
function hsBanner(c){const P=hsDecode(c);if(!P)return false;chTab('pGhosts');const d=P[0].d,pars=parsFor(d.n,d.cv,d.kind);$('ghostBanner').classList.remove('hide');$('hcpSel').style.display='none';$('btnGhost').style.display='none';
  $('ghostText').textContent='Hot-seat round · course #'+d.seed+' · '+BIOMES[biomeOf(d.seed,d.cv)].n+' · '+P.map(q=>{const t=roundTotal(q.d.log,pars,q.d.cv);return q.name+' '+(t.done<d.n?'(unfinished)':relS(t.s-t.p))}).join(' · ');
  $('bannerX').innerHTML=P.map((q,i)=>'<button class="sec" data-hv="'+i+'">vs '+esc(q.name)+'</button>').join('')+'<button class="big" id="hsW" style="font-size:15px;padding:9px 16px">Watch</button>';
  $('bannerX').querySelectorAll('[data-hv]').forEach(b=>b.onclick=()=>{const q=P[+b.dataset.hv];seedIn.value=d.seed;S.seed=d.seed;S.over=false;startRound(d.n,q.code)});$('hsW').onclick=()=>hsWatch(P);return true}
/* watching a bundle: every seat's shots replayed in the order they were played, the other balls where they lie */
function hsWatch(P){const d=P[0].d;useCalib(d.cv);Object.assign(S,{seed:d.seed,n:d.n,cv:d.cv,pars:parsFor(d.n,d.cv,d.kind),setup:d.setup,season:d.season,wear:d.wear,casual:d.casual,kind:d.kind,ball:d.ball,ghost:null,match:null,xg:null,lab:null,scen:null,guide:null,hinfo:{},over:false,log:Array.from({length:d.n},()=>[]),strokes:new Array(d.n).fill(null)});setBag(d.bag);
  S.hs={watch:P.map(q=>q.d.log),P:P.map(q=>({name:q.name,hcp:q.d.hcp==null?0:q.d.hcp,seat:q.d.seat,look:q.d.look,ball:q.d.ball,log:[],strokes:new Array(d.n).fill(null)})),cur:0,order:P.map((_,i)=>i)};
  $('title').classList.add('hide');$('hud').classList.add('on');$('tools').classList.add('on');$('bottom').classList.remove('on');AU.init();hsWatchHole(0)}
function hsWatchHole(h){const H=S.hs;S.hi=h;loadHole(h,true);H.P.forEach(p=>{p.log[h]=[]});if(h>0){const pv=p=>p.strokes[h-1]??99;H.order=H.order.slice().sort((a,b)=>pv(H.P[a])-pv(H.P[b]))}msg('Hole '+(h+1)+' · Par '+W.par,'',2);S.mode='wait';S.wait=1.4;S.next=hsWatchNext}
function hsWatchNext(){const H=S.hs,j=hsNext();if(j>=0)return hsWatchShot(j);H.P.forEach(p=>{p.strokes[S.hi]=holeTally(p.log[S.hi],p.seat).n});msg('Hole '+(S.hi+1),H.P.map(p=>esc(p.name)+' '+p.strokes[S.hi]).join(' · '),2.4);S.mode='wait';S.wait=2.6;S.next=()=>S.hi+1<S.n?hsWatchHole(S.hi+1):hsCard(true)}
function hsWatchShot(j){const H=S.hs,p=H.P[j],h=S.hi,full=H.watch[j][h]||[],L=p.log[h];while(L.length<full.length&&full[L.length].kind!==0)L.push(full[L.length]);if(L.length>=full.length)return hsWatchNext();
  const k=L.length,e=full[k],Lk=L.concat([e]),T=holeTally(Lk,p.seat)[k],o=holePath(Lk,W.pin,p.seat)[k],c=clubById(e.c),seed=shotSeed(S.seed,h,T.no,T.att);
  H.cur=j;S.look=p.look;S.seat=p.seat;S.ball=p.ball;S.stroke=T.no-1;B=PB;place(o.start[0],o.start[1]);PB.sx=o.start[0];PB.sz=o.start[1];PB.plug=o.plug;PB.lf=o.lf;selectClubId(e.c);S.shape=e.s;S.traj=e.t;S.yaw=uYaw(e.y);S.replay={watch:j,name:p.name+'\u2019s'};cutTo(snapCam);
  const pre=preSim(c,uPow(e.p),uAcc(e.a),uYaw(e.y),e.s,e.t,seed,e.k||0,o.plug,o.lf,uMis(e.m|0));hint(p.name+' · '+c.n+' · '+Math.round(MM.hyp(W.pin.x-o.start[0],W.pin.z-o.start[1]))+' m',2);
  S.mode='wait';S.wait=.8;S.next=()=>beginSwing({pow:uPow(e.p),onContact:()=>{B=PB;PB.rng=mulberry32(seed);PB.k0=e.k||0;PB.ballType=p.ball;PB.plug=o.plug;PB.lf=o.lf;strike(c,uPow(e.p),uAcc(e.a),uYaw(e.y),e.s,e.t,uMis(e.m|0));S.mode='shot';S.ff=1;S.shotEnd=S.t;S.shotCam=Object.assign(shotCamFor(pre,c),{t0:S.t});AU.play(c.putter?'putt':'hit',.8)}})}
function hsWatchEnd(){const H=S.hs,j=S.replay.watch,p=H.P[j],h=S.hi,full=H.watch[j][h],L=p.log[h],e=full[L.length];L.push(e);if(B.st==='holed'){AU.play('cup');S.holedT=S.t}else if(B.st==='water')AU.play('splash');
  const nx=full[L.length],again=!!nx&&nx.kind===0&&(nx.pv||e.mu);S.replay=null;S.wait=1.2;S.mode='wait';S.next=()=>again?hsWatchShot(j):hsWatchNext()}
const hsRestore=(v,n)=>({P:v.P.map(p=>Object.assign({},p,{strokes:new Array(n).fill(null)})),cur:v.cur|0,order:v.order||v.P.map((_,i)=>i)});
function hsResume(n){const H=S.hs;let h=0;for(;h<n;h++)if(!H.P.every(p=>holeDone(p.log[h]||[],S.pars[h])))break;H.P.forEach(p=>{for(let i=0;i<n;i++){const L=p.log[i]||[];p.strokes[i]=holeDone(L,S.pars[i])?holeStrokes(L,S.pars[i]):null}});if(h>=n){showCard();return}loadHole(h);msg('Resumed','Hole '+(h+1),2)}
function hsResult(){const H=S.hs,o=H.P[0],st=o.strokes[S.hi],d=st-W.par;if(st!=null&&S.cv>=4){if(st===1)featAdd('ace');if(d<=-2)featAdd('eagle');if(d<=-1)featAdd('birdie')}const m=hsMatch();
  $('resName').textContent='Hole '+(S.hi+1);$('resName').className='even';$('resSub').textContent=H.P.map(p=>{const x=p.strokes[S.hi];return p.name+' '+(x==null?'–':x+' · '+scoreName(x-W.par,x)[0].toLowerCase())}).join('  ·  ');$('resTotal').textContent=m?m.text:H.P.map(p=>{const t=hsTot(p);return p.name+' '+relS(t.s-t.par)}).join(' · ');$('resMatch').style.display='none'}
$('pass').onclick=hsPassEnd;
/* F-078: the whole career as a file or a code — every voxellinks key, a version and a checksum; no server */
const fnv=s=>{let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)},vlKeys=()=>{const K=[];for(let i=0;i<VS.length;i++){const k=VS.key(i);if(k&&k.startsWith('voxellinks.'))K.push(k)}return K.sort()};
function careerDump(){const keys={};for(const k of vlKeys())keys[k]=VS.getItem(k);return{v:1,t:Date.now(),keys,sum:fnv(JSON.stringify(keys))}}
const zStream=(bytes,Z)=>new Response(new Blob([bytes]).stream().pipeThrough(new Z('deflate-raw'))).arrayBuffer();
async function careerCode(){const s=JSON.stringify(careerDump());return typeof CompressionStream==='function'?'X'+b64u(new Uint8Array(await zStream(u8s(s),CompressionStream))):'Y'+b64u(u8s(s))}
async function careerParse(t){t=(t||'').trim();let s=t;if(/^[XY][A-Za-z0-9_-]+$/.test(t)){const b=ub64(t.slice(1));s=t[0]==='Y'?s8(b):s8(new Uint8Array(await zStream(b,DecompressionStream)))}
  const o=JSON.parse(s);if(!o||o.v!==1||!o.keys||fnv(JSON.stringify(o.keys))!==o.sum||Object.keys(o.keys).some(k=>!k.startsWith('voxellinks.')))throw new Error('Not a Voxel Links career, or damaged on the way');return o}
function careerSummary(o){const j=k=>{try{return JSON.parse(o.keys['voxellinks.'+k])}catch(e){return null}},c=j('career'),b=j('book'),sh=j('shots'),k=j('key');
  return[(c?(c.season||0)+' season'+(c.season===1?'':'s')+' of career':'no career'),(b?(b.rounds||[]).length+(b.drives||[]).length+(b.aces||[]).length:0)+' book entries',(sh?sh.reduce((a,r)=>a+r.rows.length,0):0)+' shots',k?'the key for '+k.name:'no key'].join(' · ')}
function careerApply(o){for(const k of vlKeys())VS.removeItem(k);for(const k in o.keys)VS.setItem(k,o.keys[k]);S.car=carLoad();S.tour=null;try{Object.assign(SETS,lsGet('voxellinks.settings',{}))}catch(e){}refreshTitle()}
/* F-079: the guided first hole — one line under the meter that moves on when you do the thing; never on the tour, never after hole 1 */
const GUIDE=['Drag to look and aim','The caddie picked a club for the distance — Q/E to change','Click to start the swing','Click again to set power — about %p% here','Click as the marker passes the white zone','That’s it — your friend sees this exact shot'],GUIDE_WAIT=4,GUIDE_DONE_T=4;
const guideWanted=()=>!!S.fromLink&&!lsGet('voxellinks.guide',0)&&!histGet().length&&!S.car&&!shotsGet().length&&!S.carRound&&S.tourRound==null&&!S.hs;
function guideStart(){S.guide=null;if(guideWanted()){S.guide={i:0};guideGo(0)}}
function guideGo(i){const G=S.guide;Object.assign(G,{i,t0:S.t,yaw0:S.yaw,club0:S.club});let t=GUIDE[i];if(i===3){const c=curClub(),d=MM.hyp(W.pin.x-PB.x,W.pin.z-PB.z);t=t.replace('%p',Math.round(100*(c.putter?Math.min(1,Math.sqrt(d/c.total)*1.06+.02):d<c.total?Math.max(.3,MM.pow(d/c.total,.75)):1)))}
  const el=$('guide');el.innerHTML=esc(t)+(i<5?' <a href="#" id="guideSkip">skip</a>':'');el.classList.remove('on');void el.offsetWidth;el.classList.add('on');const s=$('guideSkip');if(s)s.onclick=e=>{e.preventDefault();e.stopPropagation();guideEnd()};
  const part=[0,0,'meter','fill','zone',0][i];if(part){const p=$(part);p.classList.remove('pulse');void p.offsetWidth;p.classList.add('pulse')}}
function guideEnd(){if(!S.guide)return;S.guide=null;$('guide').classList.remove('on');lsSet('voxellinks.guide',1)}
function guideTick(){const G=S.guide;if(!G)return;if(S.hi>0&&!S.lab||S.mode==='title'||S.replay){guideEnd();return}const i=G.i,dt=S.t-G.t0,done=i===0?Math.abs(S.yaw-G.yaw0)>3*DEG||S.ph>0:i===1?S.club!==G.club0||dt>GUIDE_WAIT||S.ph>0:i===2?S.ph>=1:i===3?S.ph>=2||S.mode!=='aim':i===4?S.mode!=='aim':dt>GUIDE_DONE_T;
  if(done){if(i>=5)return guideEnd();if(AU.ctx&&AU.on)AU.tone(1320,1320,.09,.05,'sine');guideGo(i+1)}}
addEventListener('keydown',e=>{if(e.key==='Escape'&&S.guide)guideEnd()});
/* F-074: a club card — its name and a board per seed, every entry's full record inside, re-verified by each friend's browser */
const CLUB_MAX=24,CLUB_NAME=20;
const clubEncode=C=>'L1!'+nEnc(C.name)+C.E.map(e=>'!'+nEnc(e.name)+'~'+e.code).join('');
function clubDecode(t){const p=(t||'').trim().replace(/^.*#/,'').split('!');if(p[0]!=='L1'||p.length<2)return null;return{name:nDec(p[1]).slice(0,CLUB_NAME)||'Club',E:p.slice(2).map(x=>{const i=x.indexOf('~');return{name:nDec(x.slice(0,i)).slice(0,NAME_MAX),code:x.slice(i+1)}}).filter(e=>e.name&&decodeRound(e.code)).slice(0,CLUB_MAX)}}
function clubLoad(t,quiet){const C=clubDecode(t);if(!C)return false;S.clubCard=C;lsSet('voxellinks.clubs',{code:clubEncode(C)});C.E.forEach(clubCheck);if(!quiet)chTab('pFriends');return true}
function clubCheck(e){e.d=decodeRound(e.code);e.ok=null;vqAdd(e.code.split('.')[0],r=>{e.ok=r.ok;e.total=r.total;e.rel=r.rel;wkRedraw()});if(e.code.includes('.'))sigCheck(e.code).then(s=>{e.sig=s.ok&&s.name===e.name?1:-1;wkRedraw()})}
function clubHtml(C){const G={};C.E.forEach((e,i)=>{const d=e.d,k=d.seed+'/'+d.n+'/'+d.kind;(G[k]=G[k]||{d,rows:[]}).rows.push(e)});const me=(keyGet()||{}).name;
  return Object.values(G).map(g=>'<div class="sotr"><b>Course #'+g.d.seed+' · '+g.d.n+' holes'+(g.d.kind?' · par-3 course':'')+'</b></div>'+g.rows.sort((a,b)=>(a.ok===false)-(b.ok===false)||(a.rel??99)-(b.rel??99)).map(e=>{const t=esc(e.name)+(e.sig===1?' '+ic('key'):'')+' '+(e.ok?relS(e.rel)+' ('+e.total+')':'');return'<div class="sotr" style="'+(e.name===me?'color:var(--acc)':'')+'">'+(e.ok==null?'… ':e.ok?'✓ ':'✗ ')+(e.ok===false?'<s>'+t+'</s>':t)+(e.d.meter?' · slow meter':'')+'</div>'}).join('')).join('')||'<p class="sub">No entries yet.</p>'}
async function clubAdd(x){const C=S.clubCard;if(!C)return;let K=keyGet();if(!K){const n=$('clubMe')&&$('clubMe').value;K=await keyMake(n)}const d=decodeRound(x.code);if(!d)return;const same=C.E.find(e=>e.name===K.name&&e.d.seed===d.seed&&e.d.n===d.n&&e.d.kind===d.kind);
  if(same){if(same.ok&&same.total<=x.s)throw new Error('Your entry there is already as good');C.E.splice(C.E.indexOf(same),1)}if(C.E.length>=CLUB_MAX)throw new Error('The card is full ('+CLUB_MAX+' entries)');
  const e={name:K.name,code:await signCode(x.code)};C.E.push(e);clubCheck(e);lsSet('voxellinks.clubs',{code:clubEncode(C)});return clubEncode(C)}
/* the Friends tab: the weekly, hot-seat and the club card */
function friendsPanel(){const el=$('pFriends'),wk=isoWeek(),st=wkGet(),mine=st.hist[wk.seed],sv=loadSave(),inProg=sv&&sv.weekly===wk.seed,lb=lbUrl(),C=S.clubCard,rows=hsRows();if(lb)wkFetch();
  const gh=WK.list&&WK.seed===wk.seed?WK.list.filter(g=>g.ok).length:null,pend=WK.list&&WK.list.some(g=>g.ok==null);
  let h='<div class="tourbox"><div class="sub" style="margin:0 0 6px;color:var(--ink)"><b>The weekly</b> · week '+wk.w+' · course #'+wk.seed+' · '+BIOMES[biomeOf(wk.seed,CV)].n+' · 18 holes · '+PINS.names[WEEKLY_SETUP]+' · '+WEAR_NAMES[WEEKLY_WEAR]+' · strict · one attempt</div>';
  if(mine)h+='<div class="sub">You shot '+relS(mine.rel)+' ('+mine.s+')'+(mine.posted?' · verified by the server · '+ordn(mine.rank)+' of '+mine.of:lb?' · not posted yet <button class="sec" id="wkRe">Post</button>':' · local personal best')+'</div>';
  else if(inProg)h+='<div class="row" style="margin:4px 0"><button class="big" id="wkRes" style="font-size:15px;padding:9px 16px">Resume the weekly</button></div>';
  else if(st.cur===wk.seed)h+='<div class="sub">This week’s attempt was started and left: the weekly never restarts</div>';
  else h+='<div class="row" style="margin:4px 0"><button class="big" id="wkPlay" style="font-size:15px;padding:9px 16px">Play the weekly</button><span class="sub" style="margin:0">'+(lb?(gh==null?'fetching the field…':gh+' ghost'+(gh===1?'':'s')+' ready'+(pend?' (verifying)':'')):'personal best · no leaderboard set')+'</span></div>';
  h+='</div><div class="tourbox"><div class="sub" style="margin:0 0 6px;color:var(--ink)"><b>Hot-seat</b> · two to four on this laptop · honours on the tee, farthest from the hole next · casual rules</div>'+rows.map((r,i)=>'<div class="row hsrow" data-ball="'+r.ball+'" style="margin:3px 0"><input class="hsn" maxlength="12" placeholder="Player '+(i+1)+'" value="'+esc(r.name)+'" style="width:130px;text-align:left"><input class="hsh" maxlength="4" placeholder="hcp" value="'+esc(String(r.hcp))+'" style="width:56px"><span class="seg">'+HS_BALLS.map(b=>'<button data-b="'+b+'" class="'+(b===r.ball?'sel':'')+'" style="color:rgb('+LOOK.ball[b].map(v=>v*255|0)+')">●</button>').join('')+'</span></div>').join('')
    +'<div class="row" style="margin:6px 0 0"><button class="big" id="hs9" style="font-size:15px;padding:9px 16px">Play 9 on course #'+(Math.max(1,+seedIn.value|0))+'</button><button class="sec" id="hs3">Quick 3</button><button class="sec" id="hs18">Full 18</button><span id="hsMsg" class="sub" style="margin:0"></span></div></div>';
  h+='<div class="tourbox"><div class="sub" style="margin:0 0 6px;color:var(--ink)"><b>Club card</b> · a leaderboard passed around as a link; every friend’s browser re-verifies every round on it</div>';
  if(C){h+='<div class="sub" style="color:var(--ink)">'+esc(C.name)+' · '+C.E.length+' of '+CLUB_MAX+' entries</div>'+clubHtml(C)+'<div class="row" style="margin:6px 0 0"><button class="sec" id="clubAddB">Add my round</button><button class="sec" id="clubLink">Copy the card</button><button class="sec" id="clubNew">New club</button></div><div id="clubPick"></div>'}
  else h+='<div class="row" style="margin:4px 0"><input id="clubName" maxlength="20" placeholder="Club name" style="width:160px;text-align:left"><button class="sec" id="clubStart">Start a club</button></div><p class="help">A friend’s club card opens from the paste box on the Play tab, or straight from its link.</p>';
  el.innerHTML=h+'</div>';
  const b=id=>$(id);if(b('wkPlay'))b('wkPlay').onclick=weeklyStart;if(b('wkRes'))b('wkRes').onclick=()=>$('btnResume').onclick();if(b('wkRe'))b('wkRe').onclick=()=>{if(keyGet())weeklyPost(wk.seed).then(friendsPanel);else chTab('pSettings')};
  el.querySelectorAll('.hsrow').forEach(r=>r.querySelectorAll('[data-b]').forEach(x=>x.onclick=()=>{r.dataset.ball=x.dataset.b;r.querySelectorAll('[data-b]').forEach(y=>y.classList.toggle('sel',y===x))}));b('hs9').onclick=()=>hsStart(9);b('hs3').onclick=()=>hsStart(3);b('hs18').onclick=()=>hsStart(18);
  if(b('clubStart'))b('clubStart').onclick=()=>{const n=b('clubName').value.trim().slice(0,CLUB_NAME);if(!n)return;S.clubCard={name:n,E:[]};lsSet('voxellinks.clubs',{code:clubEncode(S.clubCard)});friendsPanel()};
  if(b('clubNew'))b('clubNew').onclick=()=>{S.clubCard=null;lsSet('voxellinks.clubs',null);friendsPanel()};if(b('clubLink'))b('clubLink').onclick=()=>linkBox('Club card','Pass it on: whoever opens it sees the board and re-verifies every entry',clubEncode(C));
  if(b('clubAddB'))b('clubAddB').onclick=()=>{const B=bookGet(),seeds=new Set(C.E.map(e=>e.d.seed)),L=B.rounds.filter(r=>r.cv>=4).sort((x,y)=>seeds.has(y.seed)-seeds.has(x.seed)||y.t-x.t).slice(0,8);
    b('clubPick').innerHTML=(keyGet()?'':'<div class="row"><input id="clubMe" maxlength="16" placeholder="Your name" style="width:140px"></div>')+(L.length?L.map((r,i)=>'<div class="sotr">'+relS(r.rel)+' ('+r.s+') · course #'+r.seed+' · '+r.n+' holes'+(seeds.has(r.seed)?' · on the card':'')+' <button class="sec" data-ca="'+i+'">Add</button></div>').join(''):'<p class="sub">Strict rounds you finish go in the record book; they can be added here.</p>')+'<div id="clubErr" class="sub"></div>';
    b('clubPick').querySelectorAll('[data-ca]').forEach(x=>x.onclick=()=>clubAdd(L[+x.dataset.ca]).then(code=>{friendsPanel();linkBox('Club card','Your round is on it. Pass it on: every friend who opens it re-verifies every entry',code)}).catch(e=>{$('clubErr').textContent=e.message}))}}
/* Settings rows for M5: the name and key, the leaderboard endpoint, the career export */
function settingsM5(el){const K=keyGet();el.insertAdjacentHTML('beforeend','<div class="setrow"><span>Your name (the key lives in this browser; no account)</span>'+(K?'<span>'+ic('key')+' '+esc(K.name)+' · key '+K.pub.slice(0,8)+'</span>':'<span><input id="setName" maxlength="16" placeholder="Name" style="width:130px"> <button class="sec" id="setKey">Make my key</button></span>')+'</div>'
  +'<div class="setrow"><span>Leaderboard endpoint (the weekly; empty keeps everything in this browser)</span><span><input id="setLb" placeholder="https://…" style="width:210px" value="'+esc(lbUrl())+'"> <button class="sec" id="setLbS">Save</button></span></div>'
  +'<div class="setrow"><span>Your career: seasons, book, stats, looks, settings and the key</span><span><button class="sec" id="exFile">Export file</button> <button class="sec" id="exCode">Export code</button> <button class="sec" id="imOpen">Import…</button></span></div>'
  +'<div id="imBox" class="hide"><textarea id="imText" rows="2" placeholder="Paste a career code" style="width:100%;font:12px ui-monospace,monospace;background:var(--field);color:var(--ink);border:1px solid var(--line);border-radius:10px;padding:8px"></textarea><div class="row"><input id="imFile" type="file" accept=".json,application/json" style="font-size:12px"><button class="sec" id="imRead">Read it</button></div><div id="imSum" class="sub"></div></div><div id="setMsg" class="sub"></div>');
  const b=id=>$(id),say=t=>{b('setMsg').textContent=t};if(b('setKey'))b('setKey').onclick=()=>keyMake(b('setName').value).then(()=>settingsPanel()).catch(e=>say(e.message));
  b('setLbS').onclick=()=>{const v=b('setLb').value.trim();if(v&&!/^https?:\/\/[^\s]+$/.test(v))return say('The endpoint is a web address (https://…)');try{if(v)VS.setItem('voxellinks.leaderboard',v);else VS.removeItem('voxellinks.leaderboard')}catch(e){}WK.list=null;say(v?'Saved: finished weekly rounds go there, signed':'Cleared: nothing leaves this browser')};
  const day=new Date().toISOString().slice(0,10);b('exFile').onclick=e=>download('voxel-links-career-'+day+'.json',JSON.stringify(careerDump()),'application/json',e.target);
  b('exCode').onclick=()=>careerCode().then(c=>linkBox('Career code','Paste it into Settings → Import on another browser · '+c.length+' characters',c,false));b('imOpen').onclick=()=>b('imBox').classList.toggle('hide');
  let pending=null;const show=o=>{pending=o;b('imSum').innerHTML='This replaces everything here with: '+esc(careerSummary(o))+' <button class="big" id="imGo" style="font-size:14px;padding:8px 14px">Replace my career</button>';b('imGo').onclick=()=>{careerApply(pending);say('Imported: '+careerSummary(pending));settingsPanel()}};
  b('imRead').onclick=async()=>{try{const f=b('imFile').files&&b('imFile').files[0];show(await careerParse(f?await f.text():b('imText').value))}catch(e){b('imSum').textContent=e.message}}}
