/* ===== v6 M6 · Leaders simulated: F-128. In a career event the field's top LEADERS (by the calibrated model) are played shot by shot by the bots at the level their rating implies (carBot, as your partner is), each leader's hole is played just after that hole loads (it reuses the hole you are on, so it costs only the bots' shots), and anything left in true idle time; their cards are their shots, their logs are ghosts you can watch, and their event totals are their shots. Everyone else keeps the calibrated score model. */
const LEADERS=3;
const LEAD={ms:[],msLive:[],busy:false},LEAD_IDLE=40;
function leadPick(){const C=S.car,R=S.carRound;if(!C||!R||!S.fieldCache||S.fieldCache.lead)return;const t=C.tier,e=R.e,pid=isMajor(t,e)?C.cur.major.partners[R.r]:C.cur.partners[e],par=S.pars.reduce((a,b)=>a+b,0);
  const rows=S.fieldCache.rows.filter(r=>r.m.id!==pid).map(r=>({r,p:r.base+r.sc.reduce((a,b)=>a+b,0)-par})).sort((a,b)=>a.p-b.p||a.r.m.id-b.r.m.id).slice(0,LEADERS);
  S.fieldCache.lead=rows.map(x=>{x.r.lead={T:carBot(C,x.r.m,e),log:[],model:x.r.sc.slice()};return x.r});leadNext()}
function leadHole(r,h){const t0=performance.now(),sv=W,svB=B,svM=MM,live=holeIs(W,h);try{if(!live)W=genHole(S.seed,h,S.pars[h],S.cv,S.setup,S);const L=withBag(botBag(r.lead.T),()=>botHole(h,r.lead.T));r.lead.log[h]=L;r.sc[h]=holeStrokes(L,S.pars[h],S.cv)}finally{W=sv;B=svB;MM=svM}(live?LEAD.msLive:LEAD.ms).push(performance.now()-t0)}
function leadTodo(){const F=S.fieldCache;if(!F||!F.lead)return null;for(let h=0;h<S.n;h++)for(const r of F.lead)if(!r.lead.log[h])return{r,h};return null}
function leadStep(dl){LEAD.busy=false;if(!S.carRound||S.mode==='title')return;const j=leadTodo();if(!j)return;if(dl&&dl.timeRemaining&&dl.timeRemaining()<LEAD_IDLE){leadNext();return}leadHole(j.r,j.h);leadNext()}
function leadNext(){if(LEAD.busy||!leadTodo())return;LEAD.busy=true;(window.requestIdleCallback?f=>requestIdleCallback(f):f=>setTimeout(f,250))(leadStep)}
function leadAt(i){const F=S.fieldCache;if(!F||!F.lead||!S.carRound||i>=S.n)return;for(const r of F.lead)if(!r.lead.log[i])leadHole(r,i)}
function leadUpTo(k){const F=S.fieldCache;if(!F||!F.lead)return;for(let h=0;h<Math.min(k,S.n);h++)for(const r of F.lead)if(!r.lead.log[h])leadHole(r,h)}
function leadResults(){const F=S.fieldCache,out={};if(!F||!F.lead)return out;leadUpTo(S.n);for(const r of F.lead)out[r.m.id]=r.sc.reduce((a,b)=>a+b,0);S.leadDone=F.lead.map(r=>({id:r.m.id,name:r.m.name,log:r.lead.log.slice(),sc:r.sc.slice(),hcp:r.lead.T.hcp,seed:S.seed,n:S.n,cv:S.cv,setup:S.setup,season:S.season,wear:S.wear}));return out}
function leadCardHtml(){const L=S.leadDone;if(!L||!L.length)return'';const par=S.pars.reduce((a,b)=>a+b,0);return'<div class="sub" style="text-align:left;margin:10px 0 4px;color:var(--ink)"><b>The leaders, shot by shot</b></div>'+L.map((x,i)=>{const tot=x.sc.reduce((a,b)=>a+b,0),best=x.sc.map((s,h)=>s-S.pars[h]).reduce((b,v,h,a)=>v<a[b]?h:b,0);return'<div class="sotr">'+esc(x.name)+' · '+relS(tot-par)+' ('+tot+') · '+x.sc.join(' ')+' <button class="sec" data-lw="'+i+'" data-lh="'+best+'"><svg class="ic" aria-hidden="true"><use href="#i-play"/></svg> Watch hole '+(best+1)+'</button></div>'}).join('')}
function leadCode(x){return encodeRound(x.seed,x.n,x.log,x.hcp,x.cv,{setup:x.setup,season:x.season,wear:x.wear,kind:0,casual:0,seat:0,ball:0,bag:DEFAULT_BAG})}
function leadBind(el){const L=S.leadDone;if(!L)return;el.querySelectorAll('[data-lw]').forEach(b=>b.onclick=()=>{AU.play('ui');const x=L[+b.dataset.lw],h=+b.dataset.lh;watchCode(leadCode(x),h,0,'pTour')})}
