/* ---- ambient sound (E-2) ---- */
const AMB={wind:null,gain:null,rain:null,next:0,beat:0,crowd:null,
  press(dt){const P=S.press,p=P&&S.cv>=4&&S.mode!=='title'&&!S.over?P.p:0,c=AU.ctx;if(!this.crowd){const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=AU.noise;s.loop=true;f.type='bandpass';f.frequency.value=520;f.Q.value=.7;g.gain.value=0;s.connect(f).connect(g).connect(AU.out());s.start();this.crowd=g}
    const address=S.ph>0||S.mode==='swing'||(S.contactT!=null&&S.t-S.contactT<1.2),ct=AU.on&&p>0&&(S.tourRound!=null||S.carRound)?(address?CROWD[1]:CROWD[0]):0;auTarget(this.crowd.gain,ct,address?.4:1.2);
    if(p>0&&AU.on&&S.heart!==false){this.beat-=dt;if(this.beat<=0){this.beat=60/(PRESS_BPM[0]+PRESS_BPM[1]*p);AU.play('beat',Math.min(1,(S.t-P.t0)/2)*(.35+.65*p))}}else this.beat=0},
  init(){if(this.wind||!AU.ctx)return;const c=AU.ctx,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=AU.noise;s.loop=true;f.type='lowpass';f.frequency.value=380;g.gain.value=0;s.connect(f).connect(g).connect(AU.out());s.start();this.wind=s;this.gain=g;
    const r=c.createBufferSource(),rf=c.createBiquadFilter(),rg=c.createGain();r.buffer=AU.noise;r.loop=true;rf.type='bandpass';rf.frequency.value=2600;rf.Q.value=.5;rg.gain.value=0;r.connect(rf).connect(rg).connect(AU.out());r.start();this.rain=rg},
  update(dt){if(!AU.ctx||!W)return;this.init();if(!this.gain)return;this.press(dt);const on=AU.on&&S.mode!=='title',target=on?.05+.03*(W.wind?W.wind.s:0):0;auTarget(this.gain.gain,target,.5);if(this.rain){const rt=on&&W.rain?.04:0;auTarget(this.rain.gain,rt,.5)}
    amb4Tick(dt);if(!on)return;this.next-=dt;if(this.next<=0){const b=W.bio;if(b===4||b===2){for(let i=0;i<3;i++)AU.tone(2600+Math.random()*900,3200+Math.random()*600,.09,.06,'sine',i*.13);this.next=6+Math.random()*8}else if(b===1){AU.tone(900,1500,.25,.05,'sawtooth');AU.tone(1500,700,.3,.04,'sawtooth',.28);this.next=9+Math.random()*11}else this.next=8}}};
