// 79-lore.js: the Codex's hand-written lore, two sentences per entry, keyed by registry key: w weapons (every
// defWeapon, hidden halves and the secret chicken included), s skills, c classes, m arenas, b campaign boss and
// mini-boss nodes (by node id), r realms (CAMP_REALMS keys), p pets and x secrets. codexLore (79-progress) reads
// these first and falls back to its generator for anything without a line. The world: the four realms (Ember
// Wastes, Frostspire, Sky Citadel, Shadow Depths), the Wicks and their guide Lumen, the Great Candle the Warlord
// put out, and the Neon league where the arenas are. Loads before 79-progress ('l' < 'p'); exposed as SC.lore.

const LORE_LINES = {
  w: {
    'fist-left': 'The off hand learns its trade from the main one and never forgives it for being second. In the Neon league the left jab is called the question, because the right is always the answer.',
    fists: 'Every duelist in the four realms starts with these and ends up back at them sooner than planned. The old masters of Wobble Hills say a fist never jams, never runs dry and never gets dropped.',
    blade: 'The plain Blade is the yardstick every smith in the Neon Foundry measures the rest against. Lumen says a Wick who can win with it can win with anything.',
    katana: 'Folded a hundred times in the forges under Frostspire, where the cold keeps the edge honest. Its draw cut is timed by heartbeat, which is why nervous duelists swing it early.',
    broadsword: 'Guards of the Sky Citadel carry it because its flat turns a bullet as well as its edge turns a blade. It was never meant to be elegant, only final.',
    greatsword: "Quarried rather than forged: the Ash Titan's armourers cut the first one from a slab of cooled slag. Carrying it is a workout; being hit by it is a lesson.",
    'dagger-left': 'The second fang, kept in the off hand and dipped in the same marsh venom as the first. Twin Fangs fighters say the left one does the talking once the right one has made its point.',
    'twin-daggers': 'Brewed in the Static Marsh by smugglers who liked to end arguments before they started. The venom wears off in a minute; the embarrassment of being nicked by both takes longer.',
    'kite-shield': "Painted with Lumen's lantern, so the last thing an attacker sees is the light they tried to put out. Bridge Keepers of the Sky Citadel retire with a hundred dents in it and not one scratch on themselves.",
    'sword-shield': 'The Guardian pair is issued to every gate warden in the four realms on their first day. Rookies hide behind the shield; veterans hide the sword behind it.',
    rapier: 'Fenced with in the glass halls of the Crystal Court, where a wide swing would shatter the furniture. Every thrust lands where the eye was a moment earlier.',
    saber: "A blade of light grown in the Neon league's workshops, humming at the pitch of the city grid. It weighs nothing, and the fights with it tend to end just as quickly.",
    'frost-blade': "Grown, not forged, from a single icicle in the Frost Queen's hall. Its chill arrives a breath before the cut, which is why the frozen never look surprised.",
    'flame-sword': 'Lit from the Great Candle before the Warlord stole its flames, and never once put out since. Pyre Wardens swear it burns hotter when the wielder is angry.',
    'war-fan': 'Dancers of the Cloud Docks fold a gale into a steel fan and open it mid-swing. The gust that follows has knocked more pirates off the quay than any cannon.',
    hammer: 'Forged for mending the roads of the Ember Wastes and borrowed for breaking everything else. The shockwave, the Slag Brutes say, is just the ground complaining.',
    'battle-axe': 'Lost Miners of the Shadow Depths swung it at roots, then at whatever was hiding in them. Its beard catches and tears, and the cut keeps bleeding long after the swing.',
    'double-axe': "The Warlord's own choice: a blade for each of the two chops he believes every problem needs. His Shades practise its whirl in the dark until the rhythm is all that is left of them.",
    mace: 'Built for the Gloamguard, who were tired of swords sliding off their armour. A clean blow rings a skull like a bell, and the ringing goes on a while.',
    bat: "A Wobble Hills kid's bat, grown up and gone to the arenas. Home-run K.O.s are counted at the Neon league and argued about for weeks.",
    'frying-pan': "Lifted from the Giant's Kitchen by a Wick who needed a shield and found a weapon. The clang has a note of its own, and the Giant has yet to notice it is missing.",
    chainsaw: 'A Robo Factory tool that forgot it was a tool. It revs louder the longer a fight goes and is the only weapon the crowd covers its ears for.',
    lollipop: 'Spun in the caramel vats of Candy Land, where everything is a weapon if you are determined enough. The sugar hits the wielder harder than the swing hits anyone.',
    spear: 'The oldest reach in the realms: a point, a pole and the patience to keep both between you and trouble. Glacier Guards hold it so long their shadows take the same stance.',
    halberd: 'Three weapons on one haft, as the gate guards of the Sky Citadel like to say, and all three are rude. Lunge, chop, repeat until the gate is clear.',
    trident: "Pulled from the Storm Lord's hoard, where it was used to steer the clouds. On the ground its prongs drag a foe down like an undertow.",
    scythe: 'The Shades carry it the way a farmer carries a tool, which is the frightening part. Its hook pulls the harvest in before the blade has finished its arc.',
    'bo-end': 'The far end of a bo staff, which strikes whoever thought they were safe behind the wielder. Monks of the Sunken Temple call it the second argument.',
    'bo-staff': "Cut from the pale wood of the Sunken Temple's drowned grove, light enough to spin all day. It hits in front and behind, so it has never once been flanked.",
    'plasma-end': "The twin staff's back end, burning the same blue as the front and just as unwilling to be ignored. Neon league engineers added it after fighters kept complaining about their blind side.",
    'plasma-staff': 'Two cells, two burning ends and a static charge that builds with every third strike. Orbital Station crews used it to clear jammed airlocks, then to clear each other.',
    flail: 'A spiked ball that goes where it likes and a chain that only pretends to steer it. Guards of the Ember Wastes stopped trying to block it a long time ago.',
    nunchaku: 'Two sticks, one short chain and a flurry faster than the eye in the Dojo Courtyard. The loose stick cracks like a whip when the swing is right and like a knuckle when it is wrong.',
    whip: 'Cured in Static Marsh resin until it moves like the snake it is named after. A full crack slows a foe, and the sound alone slows the crowd.',
    kusarigama: 'Sickle, weight and chain: a Shadow Depths tool for catching things that would rather not be caught. Root Stalkers hook you first and worry about the rest later.',
    'glove-left': "The off-hand Haymaker, laced tight and swung on the off beat. Cornermen in the Neon league say the left is the one you don't see coming because it isn't the one you were watching.",
    'boxing-gloves': 'Yeti-fur lining, Wobble Hills leather and knockback that sends people out of the arena and into the stands. The Yeti Den spars with them for the fun of it.',
    pistol: 'Six pulses from a cell charged on the Neon grid, then a click everyone in the arena hears. Scouts of the Sky Citadel carry two and still count their shots.',
    revolver: 'Each round is a small storm: slow, loud and strong enough to shove a Wick off a ledge. Dune Raiders name their six chambers after their six worst enemies.',
    shotgun: "The Cloud Docks' answer to boarding parties: six pellets, one bang and a kick that moves the shooter too. Nobody argues with it inside a doorway.",
    minigun: 'A barrel for every regret, spun up on a Robo Factory motor. It is heavy enough to slow whoever carries it, which the crowd calls fair.',
    sniper: 'Two shots that cross the whole arena while everyone else is still turning round. Gale Archers meditate between reloads, and it is not optional.',
    rocket: 'A tube, a fuse and the oldest trick in the Neon league: fire at your own feet and arrive on the roof. The second trick is landing.',
    grenade: 'Lobs grenades that bounce three times before anyone takes them seriously. The Smoke Imps of Smoke Hollow use the bounces to count down their victims.',
    crossbow: 'Fires bolts heavy enough to pin boots to the floor, which the Gloamguard found more useful than wounding. A pinned Wick fights like a tree.',
    longbow: "Strung with cord from the Moon Base's silent looms and drawn to the ear for a shot that goes straight through. The archers of the Silent Glacier never hurry it.",
    kunai: 'Three knives at once, thrown by Shades who never wait to see where the first one went. The supply never seems to run out, and nobody can explain why.',
    boomerang: 'Carved by Star Drifters from a wing that fell off something nobody could name. It returns to the thrower whether or not they are ready.',
    laser: 'A beam that is already there when you see it, pierced through two duelists at once. Three charges per cell, and no one has found a fourth.',
    plasma: "Hold it and the orb grows until it is too bright to look at; let go and it finds a wall or a face. The Thunder Spire's technicians banned it indoors.",
    flamethrower: 'Bottled in the Caldera, where the lava pools breathe the same way. The tank empties fast and the burns stay.',
    cryo: "The Frost Queen's winter in a canister, sprayed as a stream of ice shards. A long enough burst turns a brawler into furniture.",
    'storm-staff': 'Cut from the lightning rod of Storm Rooftop after one strike too many. The bolt leaps to the nearest foe and then, bored, to their friends.',
    wand: 'Each star drifts lazily toward whoever stands nearest, which makes it a terrible weapon against anyone who keeps moving. Lumen is fond of it anyway.',
    'void-orb': 'A dark bead of the Shadow Depths that opens a hungry well wherever it lands. Whisperers carry one in each pocket and never fall through the floor.',
    slingshot: 'The humblest weapon in the realms, with the pebbles of the Glass Dunes for ammunition. One clean headshot and a Dune Raider has a very bad day.',
    bubble: "Candy Land's silliest invention, sold to children until the first Wick floated clean out of an arena. Trapped foes drift up slowly enough to think about their choices.",
    confetti: 'Fired at every Neon league victory parade and, more recently, at the opponent. It barely hurts, but it shoves hard enough to end a fight on a ledge.',
    'zombie-claws': 'What the shamblers of the Haunted Graveyard use instead of manners. They swipe, they grab, and they keep coming.',
    'rubber-chicken': 'Nobody knows who first brought it into the arena; everybody remembers who lost to it. The squeak carries across the whole stadium.',
  },
  s: {
    blink: 'Taught in the Whispering Halls, where being behind someone is a way of life. Ninjas practise it until the moment of invulnerability feels longer than it is.',
    slam: 'The Slag Brutes of the Ember Wastes stomp to say hello and stomp again to say goodbye. From a height the quake is bigger, which is why they always jump first.',
    lunge: "A streak of light with a duelist inside it, slicing everyone along the line. It is named for the Sky Rail's comet season, when the sky does the same thing.",
    uppercut: 'A rising cut that launches a foe toward the clouds, named by Cloud Docks fighters who first saw the sky split above them. Gravity handles the rest.',
    rocket: "The Skyrocket's oldest trick made into a skill: blast off, scorch whoever is beside you, and look down. Rookies use it to escape; veterans use it to arrive.",
    grapple: "The Bridge Keepers' hook, flung at a wall to cross a gap or at a Wick to make a point. Being yanked across the arena is said to be a lesson in humility.",
    parry: 'Half a second of perfect calm, taught by the Rime Knight on his hundred-winter stair. The shot bounces back and the swing meets a counter before it lands.',
    fireball: 'A little piece of the Ember Flame, hurled and bursting where it lands. The Pyre Wardens used to light the Magma Gate with it every evening.',
    lightning: "The Thunder Sentinel's favourite trick: mark the ground, count to one, and let the sky do the hitting. Dodging it is a matter of listening.",
    'frost-nova': "A burst of the Frost Queen's winter that freezes everyone close enough to feel it. Ice Acolytes cast it to end conversations.",
    meteor: 'A called-down star that lands where the foe will be, not where they are. The drifters of Star Rock say it is only polite to warn them first.',
    toxic: 'Breathed out of the Static Marsh and bottled by smugglers who sell it to duelists with no patience. Standing in it is a slow way to learn.',
    tremor: "A rolling shake of the whole arena, learned from the Ash Titan's footsteps. Jump and it passes under you; stand and it argues.",
    glaive: 'A thrown blade that cuts on the way out and again on the way home. Sky Pirates juggle it between fights, which explains the missing fingers.',
    'gravity-well': 'A pocket of the Shadow Depths opened in the middle of the arena, pulling in foes, shots and the occasional orb. Then it closes, loudly.',
    repulse: "A wave of pressure that throws foes back and returns their bullets to sender. The Gloamguard use it to keep the Warlord's door shut.",
    bubble: 'A soap-thin shield from the Sunken Temple that takes two hits and then pops with dignity. The monks say the trick is not to look smug inside it.',
    mend: 'A pulse of candlelight that washes off burns, poison and slows, then knits the wounds. Lumen taught it to the first Wick who asked nicely.',
    frenzy: "Five seconds of fury, borrowed from the Warlord's Endless Night and paid for in bruises. Everything hits harder, including the floor.",
    chrono: 'A bubble of slow time from the Crystal Court, where the clocks were frozen along with everything else. Foes crawl and their bullets drift like snow.',
    decoy: 'A fragile copy of yourself that fights for five seconds and takes the blame. Whisperers of the Shadow Depths send theirs to meetings.',
    vanish: 'Three seconds of being nowhere, learned from the Shades who do it for a living. The first hit from hiding is always the rudest.',
    snare: 'A trap the Lost Miners left in the Lost Mine and the duelists took home. Step on it and you learn to fly, briefly.',
    magnet: "A pull from the Orbital Station's docking rings, pointed at a foe's weapon and anything shiny nearby. Guards wobble and orbs come running.",
  },
  c: {
    none: 'No school, no passive and no excuses: the way every Wick fought before the realms had names for styles. Lumen approves.',
    ninja: 'Trained on the rooftops of Neon City, where the third jump is the difference between a landing and a long drop. Light enough to be thrown far, quick enough to be back before it matters.',
    brute: "The Slag Bridge school: hit harder, hold on, and knock the weapon clean out of their hands. Brutes don't dodge, they arrive.",
    mage: "Students of the Crystal Court live on their cooldowns and lose on them too. A mage's super fills fast because, as they say, they were going to use it anyway.",
    gunner: 'Cloud Docks marksmen who never learned the word reload, because the ammo arrived before they needed it. One more throwable, one less reason to miss.',
    tank: "Built like the Gloamguard's door and about as easy to push. More health, more stamina, and a shrug where the knockback should be.",
    trickster: 'A Candy Land carnival act turned fighting style: dash further, vanish for a blink, and be somewhere else when the swing lands. Nobody has pinned one down twice.',
  },
  m: {
    neon: "The Neon league's home ground, three rooftops above a city that never turns its lights off. Every champion in the realms has stood on the middle ledge at least once.",
    dojo: 'Bare boards, no ledges and nowhere to hide from your own footwork. The masters of Wobble Hills sweep it at dawn and judge from the porch.',
    foundry: "Where the Neon Foundry's smiths pour the blades the whole league fights with, over a pit of the stuff they are made from. The platform slides because nobody ever fixed the chain.",
    frost: "The Frost Queen's doorstep, polished to glass by a thousand winters. Stopping takes longer here, and so does getting up.",
    moon: "An outpost of the Sky Citadel where gravity is a rumour and grenades float like thoughts. The Silent Glacier's archers trained here for the quiet.",
    sky: 'Rocks that float on wind the Storm Lord stole, with a very long way down between them. The Windward Bridge toll was never worth paying.',
    caldera: 'A crater in the Ember Wastes that breathes lava in geysers, on a schedule only the Pyre Wardens could read. Watch for the glow, then stop watching and move.',
    factory: 'The Buzzsaw and the Ripper Saw were born here, on belts that drag careless duelists toward the crushers. The lights flash before the slam, which counts as a safety feature.',
    spikepit: "Smoke Hollow's hazard of choice: a bed of spikes, a hovering bridge and three imps hoarding stars. The bridge is honest; the footing is not.",
    storm: 'The highest roof in Neon City and the one the lightning likes best. Gusts shove, strikes are marked, and the Storm Staff was cut from its rod.',
    desert: 'The Glass Dunes bury and unbury these ledges with every sandstorm. Dune Raiders fight here because the crumbling floor keeps the odds interesting.',
    temple: 'A drowned hall below Frostspire where the Hall of Icicles once stood dry. The current sways everyone, and the monks’ staffs still float past.',
    bounce: 'A Candy Land fairground that someone, unwisely, licensed as an arena. Trampolines launch duelists over each other and occasionally over the fence.',
    graveyard: 'The Gloom Gate of the Shadow Depths, where the fog only shows you what is already too close. The ghosts are polite but very cold.',
    station: 'A Sky Citadel outpost with zero-g columns and a view nobody has time to enjoy. The Gloam Door at the end is said to open into the dark itself.',
    pirate: "The Cloud Docks' flagship, rolling on a swell of air with cannonballs for weather. The red rings mark where you shouldn't be in a moment.",
    train: 'The Sky Rail, running between the floating islands into a headwind that leans on everyone. When TUNNEL flashes, drop between the cars or meet the arch.',
    jungle: "The Rootcaverns' roof, where the Root Stalkers hang vines over the spikes and the stone faces have opinions. Grab a vine and swing; the darts prefer the ground.",
    candy: 'Caramel puddles, marshmallow springs and a lollipop in every hand. It looks friendly for exactly as long as your feet are free.',
    eruption: "The Ashen Throne's own volcano, which blows mid-fight because the Ash Titan likes an audience. Ledges sink, rock rises and bombs rain on the marked spots.",
    asteroid: 'Star Rock: four planetoids with their own ideas about down, adrift beyond the Sky Citadel. Run right round one, hop to the next, and try not to miss.',
    mansion: 'The Whispering Halls, where the chandelier swings and the lights die every few seconds. In the dark only the blades glow, which is rather the point.',
    kitchen: 'A countertop somewhere above Wobble Hills, where the Giant eats and the Wicks fight between the crumbs. The toaster has launched more duelists than any skill.',
  },
  b: {
    e4: 'Warden of the Magma Gate, who swore the gate would burn for one master and meant the Warlord. His Emberbrand still carries the first flame of the Great Candle, whatever he says.',
    e5: 'A giant of cooled slag with the Ember Flame locked in his chest, where the cracks spill fire when he is hurt. He wanted to add a little Wick to his collection; the Wick had other plans.',
    f4: 'A hundred winters on the Rime Stair, guarding it against nobody in particular. He parries out of habit and freezes out of politeness.',
    f5: 'She froze her own heart so nothing could melt it, and ruled a court of statues who used to be guests. The Frost Flame remembered warmth before she did.',
    s4: "The Thunder Spire's automated doorman, running storm protocol since the Sky Citadel was built. It blinks across the spire and calls lightning on whoever follows.",
    s5: 'The wind that knocks you off the edge of the world, as he introduces himself, with a trident that steers the clouds. Lumen caught the Wick twice in that fight and mentions it often.',
    d4: 'The knight who guards the Gloam Door and is, in every way that matters, the door. Sword, shield, a Force Push and a vow that it stays shut forever.',
    d5: "He stole the Great Candle's four flames and gave them to his generals so the realms would go cold and quiet. On the Unlit Throne he fights with a Twinblade Axe and calls his Shades when the night runs long.",
  },
  r: {
    ember: 'The first realm the dark reached and the first the Wick walked: Cinder Road, the Slag Bridge, the Glass Dunes and the Ashen Throne. The Ember Flame burns loudest of the four.',
    frost: 'A peak of glass and silence where the Frost Queen froze her heart and the realm with it. The Frost Flame was found in the Crystal Court, still warm.',
    sky: 'Islands on stolen wind, docks in the clouds and a rail between them, ruled from the Eye of the Storm. The Storm Flame rides the gale.',
    shadow: "The realm under the roots, where Lumen's light fails and the Warlord keeps his Unlit Throne. The Shadow Flame is his own, and he wants the other three back.",
  },
  p: {
    none: 'Some Wicks fight alone and swear by it; the Dojo masters call solitude the oldest companion. Nothing to feed, nothing to lose.',
    bitbot: 'A Robo Factory reject with one job left in it: zap the shot that was going to hit you. It hums the Neon league anthem while it waits.',
    sprig: 'A seedling from the Rootcaverns that grew toward the first Wick who watered it. It heals when you are low and sulks when you are not.',
    zappy: "A spark that leapt off the Storm Rooftop's rod and never went back. It nips whoever stands too close and calls it play.",
    fetch: "A Wobble Hills pup who fetches the nearest orb and, if none is around, a stick, a stone or a Dune Raider's boot. Good dog.",
    tick: 'A clock from the Crystal Court that slows down anything coming at its owner. It is always a little behind and proud of it.',
    wisp: 'A flicker of the Ember Flame that followed the Wick out of the Ashen Throne. It sets foes alight for a moment and apologises in sparks.',
    bubbles: 'A fish from the Sunken Temple who swims through the air out of sheer confidence. One burst of bubbles washes a debuff clean off.',
    glim: "A mote of Lumen's lantern light that tops up your super meter when nobody is looking. It is the quietest pet and the most missed.",
  },
  x: {
    konami: "An old code from very old games, remembered by the Neon league's oldest arcade cabinet. Type it and the heads grow; nobody knows why.",
    cluck: 'The chicken that lost a championship for a Wick who refused to put it down. It squeaks in victory and in defeat.',
    shiny: 'Five shards of Crystal Court glass on a band, catching every colour the arena can throw. It is worth nothing and everyone wants it.',
    boogie: "A K.O. effect from the night the Neon league's lights were wired into the music. The crowd still gets down on the title screen.",
    nightowl: 'A title for Wicks who fight in the small hours, when the Great Candle burns lowest. The owls of the Rootcaverns approve.',
    showoff: "A jester's outfit for anyone who taunts three times in a match and still wins it. The Warlord finds it very annoying.",
  },
};

on('boot', () => { if (window.SC) SC.lore = LORE_LINES; });   // for the smoke test's coverage and uniqueness checks
